# 04 — RAG over ASIC RG 271

## Purpose

This notebook builds the first retrieval layer for the complaint intelligence platform.

The goal is to use ASIC Regulatory Guide 271 as a small knowledge base for internal dispute resolution guidance.

The workflow is:
- Load the ASIC RG 271 PDF
- Extract text from the PDF
- Split the text into smaller chunks
- Convert chunks into embeddings
- Store embeddings in a local Chroma vector database
- Retrieve the most relevant RG 271 chunks for a redacted complaint narrative

This creates the foundation for a RAG assistant that can support complaint triage with regulatory context.

In [1]:
import pandas as pd
from pathlib import Path
from pypdf import PdfReader

pd.set_option("display.max_columns", 50)
pd.set_option("display.max_colwidth", 300)

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
PDF_PATH = Path("../data/knowledge_base/rg271.pdf")

print("PDF exists:", PDF_PATH.exists())
print("PDF path:", PDF_PATH)

PDF exists: True
PDF path: ../data/knowledge_base/rg271.pdf

In [3]:
reader = PdfReader(PDF_PATH)

num_pages = len(reader.pages)

print("Number of pages:", num_pages)

Number of pages: 57

In [4]:
pages = []

for page_number, page in enumerate(reader.pages, start=1):
    text = page.extract_text()
    
    if text:
        pages.append({
            "page_number": page_number,
            "text": text
        })

pages_df = pd.DataFrame(pages)

print("Pages with extracted text:", len(pages_df))

pages_df.head()

Pages with extracted text: 57

,page_number,text
0,1,"\n \n \nREGULATORY GUIDE 271 \nInternal dispute resolution \nSeptember 2021 \nAbout this guide \nThis guide is for Australian financial services (AFS) licensees, unlicensed \nproduct issuers, unlicensed secondary sellers, trustees of regulated \nsuperannuation funds (other than self-managed sup..."
1,2,REGULATORY GUIDE 271: Internal dispute resolution \n© Australian Securities and Investments Commission September 2021 Page 2 \nAbout ASIC regulatory documents \nIn administering legislation ASIC issues the following types of regulatory \ndocuments. \nConsultation papers: seek feedback from stak...
2,3,REGULATORY GUIDE 271: Internal dispute resolution \n© Australian Securities and Investments Commission September 2021 Page 3 \nContents \nA Overview ................................................................................................. 4 \nFinancial services dispute resolution framew...
3,4,REGULATORY GUIDE 271: Internal dispute resolution \n© Australian Securities and Investments Commission September 2021 Page 4 \nA Overview \nKey points \nFinancial firms must have a dispute resolution system that consists of: \n• an internal dispute resolution (IDR) procedure that meets the sta...
4,5,"REGULATORY GUIDE 271: Internal dispute resolution \n© Australian Securities and Investments Commission September 2021 Page 5 \nNote 2: Unlicensed carried over instrument lenders (unlicensed COI lenders) have IDR \nobligations, but are not required to be a member of AFCA (see RG 271.3). \nRG 271..."

In [5]:
print(pages_df.loc[0, "text"][:1500])

REGULATORY GUIDE 271
Internal dispute resolution
September 2021
About this guide
This guide is for Australian financial services (AFS) licensees, unlicensed
product issuers, unlicensed secondary sellers, trustees of regulated
superannuation funds (other than self-managed superannuation funds
(SMSFs)), trustees of approved deposit funds, retirement savings account
providers, Australian credit licensees (credit licensees) and unlicensed
carried over instrument lenders (unlicensed COI lenders).
The standards and requirements highlighted in this guide are enforceable.
It explains what these financial firms must do to have an internal dispute
resolution (IDR) system in place that meets ASIC’s standards and
requirements.
Note: This guide comes into effect on 5 October 2021. For complaints
received by financial firms before that date, Regulatory Guide 165 Licensing:
Internal and external dispute resolution (RG 165) applies. We will withdraw
RG 165 on 5 October 2022.
This guide should be read in conjunction with Regulatory Guide 267
Oversight of the Australian Financial Complaints Authority (RG 267).

In [6]:
full_text = "\n\n".join(pages_df["text"].tolist())

print("Total characters:", len(full_text))
print("Total words:", len(full_text.split()))
print(full_text[:1000])

Total characters: 126909
Total words: 18635



REGULATORY GUIDE 271
Internal dispute resolution
September 2021
About this guide
This guide is for Australian financial services (AFS) licensees, unlicensed
product issuers, unlicensed secondary sellers, trustees of regulated
superannuation funds (other than self-managed superannuation funds
(SMSFs)), trustees of approved deposit funds, retirement savings account
providers, Australian credit licensees (credit licensees) and unlicensed
carried over instrument lenders (unlicensed COI lenders).
The standards and requirements highlighted in this guide are enforceable.
It explains what these financial firms must do to have an internal dispute
resolution (IDR) system in place that meets ASIC’s standards and
requirements.
Note: This guide comes into effect on 5 October 2021. For complaints
received by financial firms before that date, Regulatory Guide 165 Licensing:
Internal and external dispute resolution (RG 165) applies. We will withdraw
RG 165 on 5 October 2022.
T

In [7]:
import re

def clean_pdf_text(text: str) -> str:
    text = re.sub(r"\s+", " ", text)
    # Birden çok boşluk, yeni satır veya sekme karakterini tek bir boşluğa dönüştürür.
    text = text.replace(" .", ".")
    # Noktadan önceki gereksiz boşluğu kaldırır.
    text = text.replace(" ,", ",")
    # Virgülden önceki gereksiz boşluğu kaldırır.
    return text.strip()
    # Metnin başındaki ve sonundaki boşlukları temizler.

clean_text = clean_pdf_text(full_text)

print("Clean characters:", len(clean_text))
print(clean_text[:1000])

clean_text = clean_pdf_text(full_text)

print("Clean characters:", len(clean_text))
print(clean_text[:1000])

Clean characters: 124357
REGULATORY GUIDE 271 Internal dispute resolution September 2021 About this guide This guide is for Australian financial services (AFS) licensees, unlicensed product issuers, unlicensed secondary sellers, trustees of regulated superannuation funds (other than self-managed superannuation funds (SMSFs)), trustees of approved deposit funds, retirement savings account providers, Australian credit licensees (credit licensees) and unlicensed carried over instrument lenders (unlicensed COI lenders). The standards and requirements highlighted in this guide are enforceable. It explains what these financial firms must do to have an internal dispute resolution (IDR) system in place that meets ASIC’s standards and requirements. Note: This guide comes into effect on 5 October 2021. For complaints received by financial firms before that date, Regulatory Guide 165 Licensing: Internal and external dispute resolution (RG 165) applies. We will withdraw RG 165 on 5 October 2022. This guide should be read
Clean characters: 124357
REGULATORY GUIDE 271 Internal dispute resolution September 2021 About this guide This guide is for Australian financial services (AFS) licensees, unlicensed product issuers, unlicensed secondary sellers, trustees of regulated superannuation funds (other than self-managed superannuation funds (SMSFs)), trustees of approved deposit funds, retirement savings account providers, Australian credit licensees (credit licensees) and unlicensed carried over instrument lenders (unlicensed COI lenders). The standards and requirements highlighted in this guide are enforceable. It explains what these financial firms must do to have an internal dispute resolution (IDR) system in place that meets ASIC’s standards and requirements. Note: This guide comes into effect on 5 October 2021. For complaints received by financial firms before that date, Regulatory Guide 165 Licensing: Internal and external dispute resolution (RG 165) applies. We will withdraw RG 165 on 5 October 2022. This guide should be read

In [8]:
def recursive_chunk_text(
    text: str,
    chunk_size: int = 1200,
    chunk_overlap: int = 150,
    separators: list[str] = ["\n\n", "\n", ". ", "; ", ", ", " "]
) -> list[str]:
    chunks = []
    # sonuçları saklamak için boş bir liste oluşturulur
    
    def split_recursive(segment: str, seps: list[str]):
        # bir segmenti ayırmak için iç fonksiyon
        if len(segment) <= chunk_size:
            # segment boyutu sınıra uygunsa olduğu gibi döndür
            return [segment.strip()]
        
        if not seps:
            # ayırıcı kalmadıysa düz olarak parça parça ayır
            return [
                segment[i:i + chunk_size].strip()
                for i in range(0, len(segment), chunk_size - chunk_overlap)
            ]
        
        sep = seps[0]
        # ilk ayırıcıyı seç
        parts = segment.split(sep)
        # segmenti seçilen ayırıcıyla böl
        
        temp_chunks = []
        current = ""
        # geçici parça listesi ve birleştirme değişkeni
        
        for part in parts:
            candidate = current + sep + part if current else part
            # mevcut parça ile yeni parçayı birleştir
            
            if len(candidate) <= chunk_size:
                current = candidate
                # eğer birleştirilmiş parça sınıra sığarsa devam et
            else:
                if current:
                    temp_chunks.append(current.strip())
                    # mevcut parçayı kaydet
                current = part
                # yeni parçayı başlat
        
        if current:
            temp_chunks.append(current.strip())
            # döngü sonunda kalan parçayı ekle
        
        final = []
        for chunk in temp_chunks:
            if len(chunk) > chunk_size:
                final.extend(split_recursive(chunk, seps[1:]))
                # parça hala çok büyükse sonraki ayırıcılarla tekrar ayır
            else:
                final.append(chunk)
                # uygun boyuttaysa final listesine ekle
        
        return final
    
    base_chunks = split_recursive(text, separators)
    # metni başlangıç ayırıcılara göre parçala
    
    for i, chunk in enumerate(base_chunks):
        if i == 0:
            chunks.append(chunk)
            # ilk parçayı doğrudan ekle
        else:
            previous_tail = chunks[-1][-chunk_overlap:]
            # önceki parçanın son bölümünü al
            chunks.append((previous_tail + " " + chunk).strip())
            # önceki parça ile örtüşmeyi ekle
    
    return chunks
    # sonuç listesini döndür

recursive_chunks = recursive_chunk_text(clean_text)

print("Recursive chunks:", len(recursive_chunks))
print("First chunk length:", len(recursive_chunks[0]))
print(recursive_chunks[0][:1200])


recursive_chunks = recursive_chunk_text(clean_text)

print("Recursive chunks:", len(recursive_chunks))
print("First chunk length:", len(recursive_chunks[0]))
print(recursive_chunks[0][:1200])

Recursive chunks: 125
First chunk length: 1108
REGULATORY GUIDE 271 Internal dispute resolution September 2021 About this guide This guide is for Australian financial services (AFS) licensees, unlicensed product issuers, unlicensed secondary sellers, trustees of regulated superannuation funds (other than self-managed superannuation funds (SMSFs)), trustees of approved deposit funds, retirement savings account providers, Australian credit licensees (credit licensees) and unlicensed carried over instrument lenders (unlicensed COI lenders). The standards and requirements highlighted in this guide are enforceable. It explains what these financial firms must do to have an internal dispute resolution (IDR) system in place that meets ASIC’s standards and requirements. Note: This guide comes into effect on 5 October 2021. For complaints received by financial firms before that date, Regulatory Guide 165 Licensing: Internal and external dispute resolution (RG 165) applies. We will withdraw RG 165 on 5 October 2022. This guide should be read in conjunction with Regulatory Guide 267 Oversight of the Australian Financial Complaints Authority (RG 267)
Recursive chunks: 125
First chunk length: 1108
REGULATORY GUIDE 271 Internal dispute resolution September 2021 About this guide This guide is for Australian financial services (AFS) licensees, unlicensed product issuers, unlicensed secondary sellers, trustees of regulated superannuation funds (other than self-managed superannuation funds (SMSFs)), trustees of approved deposit funds, retirement savings account providers, Australian credit licensees (credit licensees) and unlicensed carried over instrument lenders (unlicensed COI lenders). The standards and requirements highlighted in this guide are enforceable. It explains what these financial firms must do to have an internal dispute resolution (IDR) system in place that meets ASIC’s standards and requirements. Note: This guide comes into effect on 5 October 2021. For complaints received by financial firms before that date, Regulatory Guide 165 Licensing: Internal and external dispute resolution (RG 165) applies. We will withdraw RG 165 on 5 October 2022. This guide should be read in conjunction with Regulatory Guide 267 Oversight of the Australian Financial Complaints Authority (RG 267)

In [9]:
for i, chunk in enumerate(recursive_chunks[:5]):
    print(f"\n--- Recursive Chunk {i} ---")
    print("Length:", len(chunk))
    print(chunk[:1000])

--- Recursive Chunk 0 ---
Length: 1108
REGULATORY GUIDE 271 Internal dispute resolution September 2021 About this guide This guide is for Australian financial services (AFS) licensees, unlicensed product issuers, unlicensed secondary sellers, trustees of regulated superannuation funds (other than self-managed superannuation funds (SMSFs)), trustees of approved deposit funds, retirement savings account providers, Australian credit licensees (credit licensees) and unlicensed carried over instrument lenders (unlicensed COI lenders). The standards and requirements highlighted in this guide are enforceable. It explains what these financial firms must do to have an internal dispute resolution (IDR) system in place that meets ASIC’s standards and requirements. Note: This guide comes into effect on 5 October 2021. For complaints received by financial firms before that date, Regulatory Guide 165 Licensing: Internal and external dispute resolution (RG 165) applies. We will withdraw RG 165 on 5 October 2022. This guide should be read

--- Recursive Chunk 1 ---
Length: 1333
5 October 2022. This guide should be read in conjunction with Regulatory Guide 267 Oversight of the Australian Financial Complaints Authority (RG 267) REGULATORY GUIDE 271: Internal dispute resolution © Australian Securities and Investments Commission September 2021 Page 2 About ASIC regulatory documents In administering legislation ASIC issues the following types of regulatory documents. Consultation papers: seek feedback from stakeholders on matters ASIC is considering, such as proposed relief or proposed regulatory guidance. Regulatory guides: give guidance to regulated entities by:  explaining when and how ASIC will exercise specific powers under legislation (primarily the Corporations Act)  explaining how ASIC interprets the law  describing the principles underlying ASIC’s approach  giving practical guidance (e.g. describing the steps of a process such as applying for a licence or giving practical examples of how regulated entities may decide to meet their obligations). Inform

--- Recursive Chunk 2 ---
Length: 1078
ts of a research project. Document history This guide was issued in September 2021 and is based on legislation and regulations as at the date of issue Previous versions:  Superseded Regulatory Guide 271, issued in July 2020  Consultation draft of Regulatory Guide 165 Internal dispute resolution, released with Consultation Paper 311 Internal dispute resolution: Update to RG 165 Disclaimer This guide does not constitute legal advice. We encourage you to seek your own professional advice to find out how the Corporations Act, National Credit Act, SIS Act and other applicable laws apply to you, as it is your responsibility to determine your obligations. REGULATORY GUIDE 271: Internal dispute resolution © Australian Securities and Investments Commission September 2021 Page 3 Contents A Overview................................................................................................. 4 Financial services dispute resolution framework..................................... 4 ASIC’s role

--- Recursive Chunk 3 ---
Length: 1349
resolution framework..................................... 4 ASIC’s role in internal dispute resolution................................................ 9 Application of the IDR requirements......................................................11 Requirements for IDR processes..........................................................11 Transition period....................................................................................12 B Application of IDR requirements........................................................13 Definition of ‘complaint’..........................................................................13 Definition of ‘complainant’......................................................................16 Outsourcing IDR processes...................................................................18 C Maximum IDR timeframes and IDR responses.................................19 Acknowledgement of complaint.............................................................19 W

--- Recursive Chunk 4 ---
Length: 1339
or multi-tier IDR processes......................31 The role of customer advocates............................................................32 Links between the IDR process and AFCA...........................................33 D Systemic issues...................................................................................34 Examples of systemic issues.................................................................34 How to manage systemic issues...........................................................34 E IDR standards......................................................................................36 Basis for the IDR standards...................................................................36 Commitment and culture........................................................................37 Enabling complaints...............................................................................37 Resourcing.........................................................................

In [10]:
from sentence_transformers import SentenceTransformer
import numpy as np

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

print("Embedding model loaded.")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Embedding model loaded.

In [11]:
def split_into_sentences(text: str) -> list[str]:
    sentences = re.split(r"(?<=[.!?])\s+", text)
    sentences = [s.strip() for s in sentences if len(s.strip()) > 30]
    return sentences

sentences = split_into_sentences(clean_text)

print("Number of sentences:", len(sentences))
print(sentences[:5])

Number of sentences: 524
['REGULATORY GUIDE 271 Internal dispute resolution September 2021 About this guide This guide is for Australian financial services (AFS) licensees, unlicensed product issuers, unlicensed secondary sellers, trustees of regulated superannuation funds (other than self-managed superannuation funds (SMSFs)), trustees of approved deposit funds, retirement savings account providers, Australian credit licensees (credit licensees) and unlicensed carried over instrument lenders (unlicensed COI lenders).', 'The standards and requirements highlighted in this guide are enforceable.', 'It explains what these financial firms must do to have an internal dispute resolution (IDR) system in place that meets ASIC’s standards and requirements.', 'Note: This guide comes into effect on 5 October 2021.', 'For complaints received by financial firms before that date, Regulatory Guide 165 Licensing: Internal and external dispute resolution (RG 165) applies.']

In [12]:
sentence_embeddings = embedding_model.encode(
    sentences,
    show_progress_bar=True,
    normalize_embeddings=True
)

print("Sentence embeddings shape:", sentence_embeddings.shape)

Batches:   0%|          | 0/17 [00:00<?, ?it/s]

Sentence embeddings shape: (524, 384)

In [13]:
similarities = []

for i in range(len(sentence_embeddings) - 1):
    sim = np.dot(sentence_embeddings[i], sentence_embeddings[i + 1])
    similarities.append(sim)

similarities = np.array(similarities)

print("Similarity min:", similarities.min())
print("Similarity mean:", similarities.mean())
print("Similarity max:", similarities.max())

Similarity min: 0.015105246
Similarity mean: 0.47839808
Similarity max: 0.9681772

In [14]:
def semantic_chunk_sentences(
    sentences: list[str],
    similarities: np.ndarray,
    percentile_threshold: int = 20,
    max_chunk_chars: int = 1600,
    min_chunk_chars: int = 500
) -> list[str]:
    threshold = np.percentile(similarities, percentile_threshold)
    
    chunks = []
    current_chunk = []
    current_length = 0
    
    for i, sentence in enumerate(sentences):
        current_chunk.append(sentence)
        current_length += len(sentence)
        
        should_split_by_similarity = (
            i < len(similarities) and similarities[i] < threshold
        )
        
        should_split_by_size = current_length >= max_chunk_chars
        
        if (should_split_by_similarity and current_length >= min_chunk_chars) or should_split_by_size:
            chunks.append(" ".join(current_chunk).strip())
            current_chunk = []
            current_length = 0
    
    if current_chunk:
        chunks.append(" ".join(current_chunk).strip())
    
    return chunks


semantic_chunks = semantic_chunk_sentences(
    sentences,
    similarities,
    percentile_threshold=20,
    max_chunk_chars=1600,
    min_chunk_chars=500
)

print("Semantic chunks:", len(semantic_chunks))
print("First semantic chunk length:", len(semantic_chunks[0]))
print(semantic_chunks[0][:1200])

Semantic chunks: 92
First semantic chunk length: 724
REGULATORY GUIDE 271 Internal dispute resolution September 2021 About this guide This guide is for Australian financial services (AFS) licensees, unlicensed product issuers, unlicensed secondary sellers, trustees of regulated superannuation funds (other than self-managed superannuation funds (SMSFs)), trustees of approved deposit funds, retirement savings account providers, Australian credit licensees (credit licensees) and unlicensed carried over instrument lenders (unlicensed COI lenders). The standards and requirements highlighted in this guide are enforceable. It explains what these financial firms must do to have an internal dispute resolution (IDR) system in place that meets ASIC’s standards and requirements.

In [15]:
for i, chunk in enumerate(semantic_chunks[:5]):
    print(f"\n--- Semantic Chunk {i} ---")
    print("Length:", len(chunk))
    print(chunk[:1000])

--- Semantic Chunk 0 ---
Length: 724
REGULATORY GUIDE 271 Internal dispute resolution September 2021 About this guide This guide is for Australian financial services (AFS) licensees, unlicensed product issuers, unlicensed secondary sellers, trustees of regulated superannuation funds (other than self-managed superannuation funds (SMSFs)), trustees of approved deposit funds, retirement savings account providers, Australian credit licensees (credit licensees) and unlicensed carried over instrument lenders (unlicensed COI lenders). The standards and requirements highlighted in this guide are enforceable. It explains what these financial firms must do to have an internal dispute resolution (IDR) system in place that meets ASIC’s standards and requirements.

--- Semantic Chunk 1 ---
Length: 1442
Note: This guide comes into effect on 5 October 2021. For complaints received by financial firms before that date, Regulatory Guide 165 Licensing: Internal and external dispute resolution (RG 165) applies. We will withdraw RG 165 on 5 October 2022. This guide should be read in conjunction with Regulatory Guide 267 Oversight of the Australian Financial Complaints Authority (RG 267). REGULATORY GUIDE 271: Internal dispute resolution © Australian Securities and Investments Commission September 2021 Page 2 About ASIC regulatory documents In administering legislation ASIC issues the following types of regulatory documents. Consultation papers: seek feedback from stakeholders on matters ASIC is considering, such as proposed relief or proposed regulatory guidance. Regulatory guides: give guidance to regulated entities by:  explaining when and how ASIC will exercise specific powers under legislation (primarily the Corporations Act)  explaining how ASIC interprets the law  describing the pri

--- Semantic Chunk 2 ---
Length: 633
Document history This guide was issued in September 2021 and is based on legislation and regulations as at the date of issue. Previous versions:  Superseded Regulatory Guide 271, issued in July 2020  Consultation draft of Regulatory Guide 165 Internal dispute resolution, released with Consultation Paper 311 Internal dispute resolution: Update to RG 165 Disclaimer This guide does not constitute legal advice. We encourage you to seek your own professional advice to find out how the Corporations Act, National Credit Act, SIS Act and other applicable laws apply to you, as it is your responsibility to determine your obligations.

--- Semantic Chunk 3 ---
Length: 3603
REGULATORY GUIDE 271: Internal dispute resolution © Australian Securities and Investments Commission September 2021 Page 3 Contents A Overview................................................................................................. 4 Financial services dispute resolution framework..................................... 4 ASIC’s role in internal dispute resolution................................................. 9 Application of the IDR requirements......................................................11 Requirements for IDR processes..........................................................11 Transition period....................................................................................12 B Application of IDR requirements........................................................13 Definition of ‘complaint’..........................................................................13 Definition of ‘complainant’.....................................................................

--- Semantic Chunk 4 ---
Length: 1525
Our dispute resolution standards and requirements are set out in: • this guide, which sets out how financial firms must meet their obligations; and • Regulatory Guide 267 Oversight of the Australian Financial Complaints Authority (RG 267), which sets out how we will administer ASIC’s powers and perform our oversight role over AFCA. We must, when considering whether to make or approve standards or requirements relating to IDR, take into account: • Australian Standard AS/NZS 10002:2014 Guidelines for complaint management in organizations (AS/NZS 10002:2014); and • any other matter we consider relevant. The standards and requirements highlighted in this guide are enforceable. This regulatory guide updates our previous IDR standards and requirements to: • give effect to the reforms introduced by the Treasury Laws Amendment (Putting Consumers First—Establishment of the Australian Financial Complaints Authority) Act 2018, which implements the Australian Government’s response to the Review of

In [16]:
## Improved PDF Text Cleaning
import re

def clean_rg271_page_text(text: str) -> str:
    if not isinstance(text, str):
        return ""
    
    # Remove common ASIC header/footer noise
    text = re.sub(r"REGULATORY GUIDE 271: Internal dispute resolution", " ", text)
    text = re.sub(r"© Australian Securities and Investments Commission", " ", text)
    text = re.sub(r"September 2021", " ", text)
    text = re.sub(r"Page \d+", " ", text)
    
    # Remove excessive dot leaders from table of contents
    text = re.sub(r"\.{5,}", " ", text)
    
    # Normalize spaces but keep paragraph-ish line breaks first
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    
    return text.strip()


pages_df["clean_page_text"] = pages_df["text"].apply(clean_rg271_page_text)

clean_text_with_breaks = "\n\n".join(pages_df["clean_page_text"].tolist())

print(clean_text_with_breaks[:2000])

REGULATORY GUIDE 271
Internal dispute resolution

About this guide
This guide is for Australian financial services (AFS) licensees, unlicensed
product issuers, unlicensed secondary sellers, trustees of regulated
superannuation funds (other than self-managed superannuation funds
(SMSFs)), trustees of approved deposit funds, retirement savings account
providers, Australian credit licensees (credit licensees) and unlicensed
carried over instrument lenders (unlicensed COI lenders).
The standards and requirements highlighted in this guide are enforceable.
It explains what these financial firms must do to have an internal dispute
resolution (IDR) system in place that meets ASIC’s standards and
requirements.
Note: This guide comes into effect on 5 October 2021. For complaints
received by financial firms before that date, Regulatory Guide 165 Licensing:
Internal and external dispute resolution (RG 165) applies. We will withdraw
RG 165 on 5 October 2022.
This guide should be read in conjunction with Regulatory Guide 267
Oversight of the Australian Financial Complaints Authority (RG 267).

About ASIC regulatory documents
In administering legislation ASIC issues the following types of regulatory
documents.
Consultation papers: seek feedback from stakeholders on matters ASIC
is considering, such as proposed relief or proposed regulatory guidance.
Regulatory guides: give guidance to regulated entities by:
 explaining when and how ASIC will exercise specific powers under
legislation (primarily the Corporations Act)
 explaining how ASIC interprets the law
 describing the principles underlying ASIC’s approach
 giving practical guidance (e.g. describing the steps of a process such
as applying for a licence or giving practical examples of how
regulated entities may decide to meet their obligations).
Information sheets: provide concise guidance on a specific process or
compliance issue or an overview of detailed guidance.
Reports: describe ASIC co

In [17]:
# Contents kısmını çıkaralım su an chunk’lara “Contents A Overview…” gibi işe yaramaz bölüm giriyor. RAG için bu zayıf context.
def remove_table_of_contents(text: str) -> str:
    # RG 271 contents page usually starts with "Contents" and ends around "A Overview"
    pattern = r"Contents\s+A Overview.*?(?=\nA Overview|\nA\s+Overview)"
    cleaned = re.sub(pattern, " ", text, flags=re.DOTALL)
    return cleaned.strip()

clean_rg271_text = remove_table_of_contents(clean_text_with_breaks)

print("Characters after cleaning:", len(clean_rg271_text))
print(clean_rg271_text[:2000])

Characters after cleaning: 116453
REGULATORY GUIDE 271
Internal dispute resolution

About this guide
This guide is for Australian financial services (AFS) licensees, unlicensed
product issuers, unlicensed secondary sellers, trustees of regulated
superannuation funds (other than self-managed superannuation funds
(SMSFs)), trustees of approved deposit funds, retirement savings account
providers, Australian credit licensees (credit licensees) and unlicensed
carried over instrument lenders (unlicensed COI lenders).
The standards and requirements highlighted in this guide are enforceable.
It explains what these financial firms must do to have an internal dispute
resolution (IDR) system in place that meets ASIC’s standards and
requirements.
Note: This guide comes into effect on 5 October 2021. For complaints
received by financial firms before that date, Regulatory Guide 165 Licensing:
Internal and external dispute resolution (RG 165) applies. We will withdraw
RG 165 on 5 October 2022.
This guide should be read in conjunction with Regulatory Guide 267
Oversight of the Australian Financial Complaints Authority (RG 267).

About ASIC regulatory documents
In administering legislation ASIC issues the following types of regulatory
documents.
Consultation papers: seek feedback from stakeholders on matters ASIC
is considering, such as proposed relief or proposed regulatory guidance.
Regulatory guides: give guidance to regulated entities by:
 explaining when and how ASIC will exercise specific powers under
legislation (primarily the Corporations Act)
 explaining how ASIC interprets the law
 describing the principles underlying ASIC’s approach
 giving practical guidance (e.g. describing the steps of a process such
as applying for a licence or giving practical examples of how
regulated entities may decide to meet their obligations).
Information sheets: provide concise guidance on a specific process or
compliance issue or an overview of detailed guidance.
Reports: describe ASIC co

In [18]:
## Method A — Section-Aware Chunking
def section_aware_chunking(text: str, max_chunk_chars: int = 1800, overlap_chars: int = 150):
    """
    Split RG 271 text using section-like boundaries first, then size-control within each section.
    This is better for regulatory PDFs because it preserves legal / policy structure.
    """
    
    # Common RG 271 section boundaries
    section_pattern = r"(?=\n[A-Z]\s+[A-Z][^\n]{3,80})"
    raw_sections = re.split(section_pattern, text)
    raw_sections = [s.strip() for s in raw_sections if len(s.strip()) > 200]
    
    chunks = []
    
    for section in raw_sections:
        if len(section) <= max_chunk_chars:
            chunks.append(section)
        else:
            # sentence-aware fallback inside long sections
            sentences = re.split(r"(?<=[.!?])\s+", section)
            current = ""
            
            for sentence in sentences:
                candidate = (current + " " + sentence).strip()
                
                if len(candidate) <= max_chunk_chars:
                    current = candidate
                else:
                    if current:
                        chunks.append(current)
                    current = sentence
            
            if current:
                chunks.append(current)
    
    # add light overlap
    overlapped_chunks = []
    for i, chunk in enumerate(chunks):
        if i == 0:
            overlapped_chunks.append(chunk)
        else:
            previous_tail = overlapped_chunks[-1][-overlap_chars:]
            overlapped_chunks.append((previous_tail + " " + chunk).strip())
    
    return overlapped_chunks


section_chunks = section_aware_chunking(clean_rg271_text)

print("Section-aware chunks:", len(section_chunks))
print("First chunk length:", len(section_chunks[0]))
print(section_chunks[0][:1200])

Section-aware chunks: 74
First chunk length: 1679
REGULATORY GUIDE 271
Internal dispute resolution

About this guide
This guide is for Australian financial services (AFS) licensees, unlicensed
product issuers, unlicensed secondary sellers, trustees of regulated
superannuation funds (other than self-managed superannuation funds
(SMSFs)), trustees of approved deposit funds, retirement savings account
providers, Australian credit licensees (credit licensees) and unlicensed
carried over instrument lenders (unlicensed COI lenders). The standards and requirements highlighted in this guide are enforceable. It explains what these financial firms must do to have an internal dispute
resolution (IDR) system in place that meets ASIC’s standards and
requirements. Note: This guide comes into effect on 5 October 2021. For complaints
received by financial firms before that date, Regulatory Guide 165 Licensing:
Internal and external dispute resolution (RG 165) applies. We will withdraw
RG 165 on 5 October 2022. This guide should be read in conjunction with Regulatory Guide 267
Oversight of the Australian Financial Complaints Authority (RG 267). About ASIC regulatory documents
In administering legislation ASIC issues the following t

In [19]:
for i, chunk in enumerate(section_chunks[:8]):
    print(f"\n--- Section-aware Chunk {i} ---")
    print("Length:", len(chunk))
    print(chunk[:1200])

--- Section-aware Chunk 0 ---
Length: 1679
REGULATORY GUIDE 271
Internal dispute resolution

About this guide
This guide is for Australian financial services (AFS) licensees, unlicensed
product issuers, unlicensed secondary sellers, trustees of regulated
superannuation funds (other than self-managed superannuation funds
(SMSFs)), trustees of approved deposit funds, retirement savings account
providers, Australian credit licensees (credit licensees) and unlicensed
carried over instrument lenders (unlicensed COI lenders). The standards and requirements highlighted in this guide are enforceable. It explains what these financial firms must do to have an internal dispute
resolution (IDR) system in place that meets ASIC’s standards and
requirements. Note: This guide comes into effect on 5 October 2021. For complaints
received by financial firms before that date, Regulatory Guide 165 Licensing:
Internal and external dispute resolution (RG 165) applies. We will withdraw
RG 165 on 5 October 2022. This guide should be read in conjunction with Regulatory Guide 267
Oversight of the Australian Financial Complaints Authority (RG 267). About ASIC regulatory documents
In administering legislation ASIC issues the following t

--- Section-aware Chunk 1 ---
Length: 1158
Corporations Act)
 explaining how ASIC interprets the law
 describing the principles underlying ASIC’s approach
 giving practical guidance (e.g. describing the steps of a process such
as applying for a licence or giving practical examples of how
regulated entities may decide to meet their obligations). Information sheets: provide concise guidance on a specific process or
compliance issue or an overview of detailed guidance. Reports: describe ASIC compliance or relief activity or the results of a
research project. Document history
This guide was issued in and is based on legislation and
regulations as at the date of issue. Previous versions:
 Superseded Regulatory Guide 271, issued in July 2020
 Consultation draft of Regulatory Guide 165 Internal dispute resolution,
released with Consultation Paper 311 Internal dispute resolution:
Update to RG 165
Disclaimer
This guide does not constitute legal advice. We encourage you to seek your
own professional advice to find out how the Corporations Act, National Credit
Act, SIS Act and other applicable laws apply to you, as it is your
responsibility to determine your obligations.

--- Section-aware Chunk 2 ---
Length: 1725
e Corporations Act, National Credit
Act, SIS Act and other applicable laws apply to you, as it is your
responsibility to determine your obligations. A Overview
Key points
Financial firms must have a dispute resolution system that consists of:
• an internal dispute resolution (IDR) procedure that meets the standards
or requirements made or approved by ASIC; and
• membership of the Australian Financial Complaints Authority (AFCA). Our dispute resolution standards and requirements are set out in:
• this guide, which sets out how financial firms must meet their obligations;
and
• Regulatory Guide 267 Oversight of the Australian Financial Complaints
Authority (RG 267), which sets out how we will administer ASIC’s
powers and perform our oversight role over AFCA. We must, when considering whether to make or approve standards or
requirements relating to IDR, take into account:
• Australian Standard AS/NZS 10002:2014 Guidelines for complaint
management in organizations (AS/NZS 10002:2014); and
• any other matter we consider relevant. The standards and requirements highlighted in this guide are enforceable. This regulatory guide updates our previous IDR standards and
require

--- Section-aware Chunk 3 ---
Length: 1919
for effective complaints handling set out in
AS/NZS 10002:2014; and
• refine our requirements in some key areas based on our regulatory
experience. Financial services dispute resolution framework
RG 271.1 Financial firms must have in place a dispute resolution system that consists of:
(a) an IDR procedure that complies with standards and requirements made
or approved by ASIC; and
(b) membership of AFCA. Note 1: See s912A(1)(g) and 1017G(1) of the Corporations Act 2001 (Corporations
Act), s47(1)(h) and (i) of the National Consumer Credit Protection Act 2009 (National
Credit Act), s101(1) and (1A) of the Superannuation Industry (Supervision) Act 1993
(SIS Act), and s47(1) and (2) of the Retirement Savings Account Act 1997 (RSA Act). Note 2: Unlicensed carried over instrument lenders (unlicensed COI lenders) have IDR
obligations, but are not required to be a member of AFCA (see RG 271.3). RG 271.2 Most financial firms also have a requirement to comply with their IDR
procedures: see modified s912A(1)(g) and 1017G(1) of the Corporations
Act, and modified s47(1)(h) and (i) of the National Credit Act. RG 271.3 A modified regulatory regime applies to some unlicensed credit fir

--- Section-aware Chunk 4 ---
Length: 1933
Act
(inserted by Sch 2 to the National Credit Regulations). RG 271.4 Table 1 sets out the dispute resolution requirements by type of financial firm. Table 1: Legislative dispute resolution requirements by firm type
Firm type Description Dispute resolution requirements
Australian
financial
services (AFS)
licensees
An AFS licensee is a business carrying
out financial services. This includes
businesses that:
 provide financial product advice to
clients;
 deal in a financial product;
 make a market for a financial product;
 operate a registered scheme;
 provide a custodial or depository
service; or
 provide traditional trustee company
services (traditional services). AFS licensees must have a dispute resolution
system that consists of:
 an IDR procedure that complies with the
standards and requirements made or
approved by ASIC (set out in this guide) that
cover complaints made by retail clients in
relation to the financial services provided; and
 membership of AFCA. AFS licensees must also comply with their IDR
procedure. Note: See s912A(1)(g) of the Corporations Act. Unlicensed
product issuers
and unlicensed
secondary
sellers
An unlicensed produc

--- Section-aware Chunk 5 ---
Length: 1770
services provided; and
 membership of AFCA. Unlicensed product issuers and unlicensed
secondary sellers must also comply with their
IDR processes. Note: See s1017G(2) of the Corporations Act. Firm type Description Dispute resolution requirements
Superannuation
trustees
A trustee of a regulated superannuation
fund (other than a self-managed
superannuation fund (SMSF)), trustee
of an approved deposit fund or a
retirement savings account (RSA)
provider. Superannuation trustees must:
 be a member of AFCA; and
 have an IDR procedure that complies with the
standards and requirements set out in
s912A(2)(a)(i) of the Corporations Act. Note 1: See also s101(1)(a)–(c) of the SIS Act. Note 2: However, s101(1)(a)–(c) of the SIS Act does
not apply to a trustee if the trustee is required under the
Corporations Act to have a dispute resolution system
complying with s912A(2) or 1017G(2) of the Act. Australian credit
licensees (credit
licensees)
Credit providers and lessors, including
those who are assigned the contractual
rights of a credit provider or lessor
(which can include debt collectors who
purchase a debt from a credit provider
or lessor). Credit service provid

--- Section-aware Chunk 6 ---
Length: 1936
ntatives engage in; and
 membership of AFCA. Credit licensees must also comply with their IDR
procedures. Note: See s47 of the National Credit Act. Credit
representatives
A credit representative is a person
authorised to engage in specified credit
activities on behalf of a credit licensee
under s64(2) or 65(2) of the National
Credit Act. The employees and
directors of a credit licensee do not
need to be formally authorised—they
act as representatives of the credit
licensee without a specific
authorisation. A person can also be
authorised as a credit representative by
more than one credit licensee. Credit representatives do not need to have IDR
processes that meet the standards and
requirements made or approved by ASIC. This
is because a credit licensee’s IDR process must
cover disputes relating to its credit representatives. Most credit representatives are required to be
separate members of AFCA: see s64 and 65 of
the National Credit Act. However, a person who has been sub-
authorised under s65(1) of the National Credit
Act and is an employee or director of the body
corporate that gave the sub-authorisation does
not need to be a separate member of AFCA. Not

--- Section-aware Chunk 7 ---
Length: 1885
not to obtain a credit
licence (or to restrict their activities to
their carried over instruments, and
subsequently cancel their credit
licence). Note: A ‘prescribed unlicensed COI
lender’ is an unlicensed COI lender who
fails to meet certain probity requirements
and who has restrictions placed on their
conduct in relation to their carried over
instruments. A prescribed unlicensed COI
lender must not engage in credit activities
with respect to their carried over
instruments (other than the activities
engaged in solely by being the credit
provider or lessor). They must instead
appoint a credit licensee to act as a
‘representative’ to engage in credit
activities on their behalf with respect to
their carried over instruments. Unlicensed COI lenders (including prescribed
unlicensed COI lenders):
 must have an IDR procedure that complies
with the standards and requirements made or
approved by ASIC (set out in this guide) that
cover complaints in relation to the credit
activities they engage in with respect to their
carried over instruments; and
 may choose to join AFCA. Unlicensed COI lenders must also comply with
their IDR procedure. Note 1: Details of the

In [20]:
## Method B — Improved Semantic Chunking
def split_into_sentences(text: str) -> list[str]:
    sentences = re.split(r"(?<=[.!?])\s+", text)
    sentences = [s.strip() for s in sentences if len(s.strip()) > 40]
    return sentences

sentences = split_into_sentences(clean_rg271_text)

print("Number of sentences:", len(sentences))
print(sentences[:5])

Number of sentences: 521
['REGULATORY GUIDE 271 \nInternal dispute resolution \n \nAbout this guide \nThis guide is for Australian financial services (AFS) licensees, unlicensed \nproduct issuers, unlicensed secondary sellers, trustees of regulated \nsuperannuation funds (other than self-managed superannuation funds \n(SMSFs)), trustees of approved deposit funds, retirement savings account \nproviders, Australian credit licensees (credit licensees) and unlicensed \ncarried over instrument lenders (unlicensed COI lenders).', 'The standards and requirements highlighted in this guide are enforceable.', 'It explains what these financial firms must do to have an internal dispute \nresolution (IDR) system in place that meets ASIC’s standards and \nrequirements.', 'Note: This guide comes into effect on 5 October 2021.', 'For complaints \nreceived by financial firms before that date, Regulatory Guide 165 Licensing: \nInternal and external dispute resolution (RG 165) applies.']

In [21]:
from sentence_transformers import SentenceTransformer
import numpy as np

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

sentence_embeddings = embedding_model.encode(
    sentences,
    show_progress_bar=True,
    normalize_embeddings=True
)

similarities = np.array([
    np.dot(sentence_embeddings[i], sentence_embeddings[i + 1])
    for i in range(len(sentence_embeddings) - 1)
])

print("Similarity min:", similarities.min())
print("Similarity mean:", similarities.mean())
print("Similarity max:", similarities.max())

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/17 [00:00<?, ?it/s]

Similarity min: 0.015105246
Similarity mean: 0.48143506
Similarity max: 0.9681772

In [22]:
def improved_semantic_chunking(
    sentences: list[str],
    similarities: np.ndarray,
    percentile_threshold: int = 25,
    max_chunk_chars: int = 1400,
    min_chunk_chars: int = 450
) -> list[str]:
    
    threshold = np.percentile(similarities, percentile_threshold)
    
    chunks = []
    current_chunk = []
    current_length = 0
    
    for i, sentence in enumerate(sentences):
        current_chunk.append(sentence)
        current_length += len(sentence)
        
        semantic_break = i < len(similarities) and similarities[i] < threshold
        size_break = current_length >= max_chunk_chars
        
        if (semantic_break and current_length >= min_chunk_chars) or size_break:
            chunks.append(" ".join(current_chunk).strip())
            current_chunk = []
            current_length = 0
    
    if current_chunk:
        chunks.append(" ".join(current_chunk).strip())
    
    return chunks


semantic_chunks_v2 = improved_semantic_chunking(
    sentences,
    similarities,
    percentile_threshold=25,
    max_chunk_chars=1400,
    min_chunk_chars=450
)

print("Improved semantic chunks:", len(semantic_chunks_v2))
print("First chunk length:", len(semantic_chunks_v2[0]))
print(semantic_chunks_v2[0][:1200])

Improved semantic chunks: 101
First chunk length: 565
REGULATORY GUIDE 271
Internal dispute resolution

About this guide
This guide is for Australian financial services (AFS) licensees, unlicensed
product issuers, unlicensed secondary sellers, trustees of regulated
superannuation funds (other than self-managed superannuation funds
(SMSFs)), trustees of approved deposit funds, retirement savings account
providers, Australian credit licensees (credit licensees) and unlicensed
carried over instrument lenders (unlicensed COI lenders). The standards and requirements highlighted in this guide are enforceable.

In [23]:
for i, chunk in enumerate(semantic_chunks_v2[:8]):
    print(f"\n--- Semantic v2 Chunk {i} ---")
    print("Length:", len(chunk))
    print(chunk[:1200])

--- Semantic v2 Chunk 0 ---
Length: 565
REGULATORY GUIDE 271
Internal dispute resolution

About this guide
This guide is for Australian financial services (AFS) licensees, unlicensed
product issuers, unlicensed secondary sellers, trustees of regulated
superannuation funds (other than self-managed superannuation funds
(SMSFs)), trustees of approved deposit funds, retirement savings account
providers, Australian credit licensees (credit licensees) and unlicensed
carried over instrument lenders (unlicensed COI lenders). The standards and requirements highlighted in this guide are enforceable.

--- Semantic v2 Chunk 1 ---
Length: 1491
It explains what these financial firms must do to have an internal dispute
resolution (IDR) system in place that meets ASIC’s standards and
requirements. Note: This guide comes into effect on 5 October 2021. For complaints
received by financial firms before that date, Regulatory Guide 165 Licensing:
Internal and external dispute resolution (RG 165) applies. We will withdraw
RG 165 on 5 October 2022. This guide should be read in conjunction with Regulatory Guide 267
Oversight of the Australian Financial Complaints Authority (RG 267). About ASIC regulatory documents
In administering legislation ASIC issues the following types of regulatory
documents. Consultation papers: seek feedback from stakeholders on matters ASIC
is considering, such as proposed relief or proposed regulatory guidance. Regulatory guides: give guidance to regulated entities by:
 explaining when and how ASIC will exercise specific powers under
legislation (primarily the Corporations Act)
 explaining how ASIC interprets the law
 describing the principles underlying ASIC’s approach
 giving practical guidance (e.g. describing the steps of a process such
as applying for a licence or giving practical

--- Semantic v2 Chunk 2 ---
Length: 629
Document history
This guide was issued in and is based on legislation and
regulations as at the date of issue. Previous versions:
 Superseded Regulatory Guide 271, issued in July 2020
 Consultation draft of Regulatory Guide 165 Internal dispute resolution,
released with Consultation Paper 311 Internal dispute resolution:
Update to RG 165
Disclaimer
This guide does not constitute legal advice. We encourage you to seek your
own professional advice to find out how the Corporations Act, National Credit
Act, SIS Act and other applicable laws apply to you, as it is your
responsibility to determine your obligations.

--- Semantic v2 Chunk 3 ---
Length: 1574
A Overview
Key points
Financial firms must have a dispute resolution system that consists of:
• an internal dispute resolution (IDR) procedure that meets the standards
or requirements made or approved by ASIC; and
• membership of the Australian Financial Complaints Authority (AFCA). Our dispute resolution standards and requirements are set out in:
• this guide, which sets out how financial firms must meet their obligations;
and
• Regulatory Guide 267 Oversight of the Australian Financial Complaints
Authority (RG 267), which sets out how we will administer ASIC’s
powers and perform our oversight role over AFCA. We must, when considering whether to make or approve standards or
requirements relating to IDR, take into account:
• Australian Standard AS/NZS 10002:2014 Guidelines for complaint
management in organizations (AS/NZS 10002:2014); and
• any other matter we consider relevant. The standards and requirements highlighted in this guide are enforceable. This regulatory guide updates our previous IDR standards and
requirements to:
• give effect to the reforms introduced by the Treasury Laws Amendment
(Putting Consumers First—Establishment of the Australian Financial


--- Semantic v2 Chunk 4 ---
Length: 599
Financial services dispute resolution framework
RG 271.1 Financial firms must have in place a dispute resolution system that consists of:
(a) an IDR procedure that complies with standards and requirements made
or approved by ASIC; and
(b) membership of AFCA. Note 1: See s912A(1)(g) and 1017G(1) of the Corporations Act 2001 (Corporations
Act), s47(1)(h) and (i) of the National Consumer Credit Protection Act 2009 (National
Credit Act), s101(1) and (1A) of the Superannuation Industry (Supervision) Act 1993
(SIS Act), and s47(1) and (2) of the Retirement Savings Account Act 1997 (RSA Act).

--- Semantic v2 Chunk 5 ---
Length: 452
Note 2: Unlicensed carried over instrument lenders (unlicensed COI lenders) have IDR
obligations, but are not required to be a member of AFCA (see RG 271.3). RG 271.2 Most financial firms also have a requirement to comply with their IDR
procedures: see modified s912A(1)(g) and 1017G(1) of the Corporations
Act, and modified s47(1)(h) and (i) of the National Credit Act. RG 271.3 A modified regulatory regime applies to some unlicensed credit firms.

--- Semantic v2 Chunk 6 ---
Length: 626
Credit
representatives and exempt special purpose funding entities (exempt SPFEs)
(including securitisation bodies) do not have IDR obligations, but must be a
member of AFCA. Unlicensed carried over instrument lenders (unlicensed
COI lenders) have IDR obligations but are not required to be a member of
AFCA. Note: See s64 and 65 of the National Credit Act, and regs 23B and 23C of the National
Consumer Credit Protection Regulations 2010 (National Credit Regulations); see also
reg 25E of the National Credit Regulations and s47(1)(e) of the National Credit Act
(inserted by Sch 2 to the National Credit Regulations).

--- Semantic v2 Chunk 7 ---
Length: 634
RG 271.4 Table 1 sets out the dispute resolution requirements by type of financial firm. Table 1: Legislative dispute resolution requirements by firm type
Firm type Description Dispute resolution requirements
Australian
financial
services (AFS)
licensees
An AFS licensee is a business carrying
out financial services. This includes
businesses that:
 provide financial product advice to
clients;
 deal in a financial product;
 make a market for a financial product;
 operate a registered scheme;
 provide a custodial or depository
service; or
 provide traditional trustee company
services (traditional services).

In [24]:
chunk_comparison_v2 = pd.DataFrame([
    {
        "method": "recursive_v1",
        "num_chunks": len(recursive_chunks),
        "avg_chunk_chars": round(np.mean([len(c) for c in recursive_chunks]), 1),
        "min_chunk_chars": min(len(c) for c in recursive_chunks),
        "max_chunk_chars": max(len(c) for c in recursive_chunks),
        "manual_quality": "poor - cuts across structure"
    },
    {
        "method": "section_aware",
        "num_chunks": len(section_chunks),
        "avg_chunk_chars": round(np.mean([len(c) for c in section_chunks]), 1),
        "min_chunk_chars": min(len(c) for c in section_chunks),
        "max_chunk_chars": max(len(c) for c in section_chunks),
        "manual_quality": "expected better for regulatory PDF"
    },
    {
        "method": "semantic_v2",
        "num_chunks": len(semantic_chunks_v2),
        "avg_chunk_chars": round(np.mean([len(c) for c in semantic_chunks_v2]), 1),
        "min_chunk_chars": min(len(c) for c in semantic_chunks_v2),
        "max_chunk_chars": max(len(c) for c in semantic_chunks_v2),
        "manual_quality": "expected better for topic shifts"
    }
])

chunk_comparison_v2

,method,num_chunks,avg_chunk_chars,min_chunk_chars,max_chunk_chars,manual_quality
0,recursive_v1,125,1142.5,223,1351,poor - cuts across structure
1,section_aware,74,1716.8,444,1949,expected better for regulatory PDF
2,semantic_v2,101,1148.3,452,3162,expected better for topic shifts

## Method C — Paragraph / Clause-Aware Chunking

This method is designed for regulatory documents such as ASIC RG 271.

Instead of splitting only by character length or semantic distance, it tries to preserve paragraph and clause structure.

The goal is to create chunks that:
- do not cut words or sentences in the middle,
- preserve regulatory context,
- avoid very small orphan chunks,
- avoid very large mixed-topic chunks,
- remain readable as standalone retrieval units.

In [25]:
def extract_paragraphs(text: str) -> list[str]:
    """
    Extract paragraph-like blocks from cleaned PDF text.
    Keeps meaningful blocks and removes very short/noisy fragments.
    """
    raw_blocks = re.split(r"\n\s*\n", text)
    
    paragraphs = []
    
    for block in raw_blocks:
        block = block.strip()
        block = re.sub(r"\s+", " ", block)
        
        # remove very short fragments
        if len(block) < 80:
            continue
        
        # remove obvious table-of-contents style fragments
        if "Contents" in block and "Overview" in block and "Application" in block:
            continue
        
        paragraphs.append(block)
    
    return paragraphs


paragraphs = extract_paragraphs(clean_rg271_text)

print("Number of paragraphs:", len(paragraphs))

for i, p in enumerate(paragraphs[:5]):
    print(f"\n--- Paragraph {i} ---")
    print("Length:", len(p))
    print(p[:800])

Number of paragraphs: 57

--- Paragraph 0 ---
Length: 1045
About this guide This guide is for Australian financial services (AFS) licensees, unlicensed product issuers, unlicensed secondary sellers, trustees of regulated superannuation funds (other than self-managed superannuation funds (SMSFs)), trustees of approved deposit funds, retirement savings account providers, Australian credit licensees (credit licensees) and unlicensed carried over instrument lenders (unlicensed COI lenders). The standards and requirements highlighted in this guide are enforceable. It explains what these financial firms must do to have an internal dispute resolution (IDR) system in place that meets ASIC’s standards and requirements. Note: This guide comes into effect on 5 October 2021. For complaints received by financial firms before that date, Regulatory Guide 165 Lic

--- Paragraph 1 ---
Length: 1553
About ASIC regulatory documents In administering legislation ASIC issues the following types of regulatory documents. Consultation papers: seek feedback from stakeholders on matters ASIC is considering, such as proposed relief or proposed regulatory guidance. Regulatory guides: give guidance to regulated entities by:  explaining when and how ASIC will exercise specific powers under legislation (primarily the Corporations Act)  explaining how ASIC interprets the law  describing the principles underlying ASIC’s approach  giving practical guidance (e.g. describing the steps of a process such as applying for a licence or giving practical examples of how regulated entities may decide to meet their obligations). Information sheets: provide concise guidance on a specific process or compliance

--- Paragraph 2 ---
Length: 2143
A Overview Key points Financial firms must have a dispute resolution system that consists of: • an internal dispute resolution (IDR) procedure that meets the standards or requirements made or approved by ASIC; and • membership of the Australian Financial Complaints Authority (AFCA). Our dispute resolution standards and requirements are set out in: • this guide, which sets out how financial firms must meet their obligations; and • Regulatory Guide 267 Oversight of the Australian Financial Complaints Authority (RG 267), which sets out how we will administer ASIC’s powers and perform our oversight role over AFCA. We must, when considering whether to make or approve standards or requirements relating to IDR, take into account: • Australian Standard AS/NZS 10002:2014 Guidelines for complaint ma

--- Paragraph 3 ---
Length: 2940
Note 2: Unlicensed carried over instrument lenders (unlicensed COI lenders) have IDR obligations, but are not required to be a member of AFCA (see RG 271.3). RG 271.2 Most financial firms also have a requirement to comply with their IDR procedures: see modified s912A(1)(g) and 1017G(1) of the Corporations Act, and modified s47(1)(h) and (i) of the National Credit Act. RG 271.3 A modified regulatory regime applies to some unlicensed credit firms. Credit representatives and exempt special purpose funding entities (exempt SPFEs) (including securitisation bodies) do not have IDR obligations, but must be a member of AFCA. Unlicensed carried over instrument lenders (unlicensed COI lenders) have IDR obligations but are not required to be a member of AFCA. Note: See s64 and 65 of the National Cred

--- Paragraph 4 ---
Length: 2616
Firm type Description Dispute resolution requirements Superannuation trustees A trustee of a regulated superannuation fund (other than a self-managed superannuation fund (SMSF)), trustee of an approved deposit fund or a retirement savings account (RSA) provider. Superannuation trustees must:  be a member of AFCA; and  have an IDR procedure that complies with the standards and requirements set out in s912A(2)(a)(i) of the Corporations Act. Note 1: See also s101(1)(a)–(c) of the SIS Act. Note 2: However, s101(1)(a)–(c) of the SIS Act does not apply to a trustee if the trustee is required under the Corporations Act to have a dispute resolution system complying with s912A(2) or 1017G(2) of the Act. Australian credit licensees (credit licensees) Credit providers and lessors, including those w

In [26]:
def split_long_paragraph(paragraph: str, max_chars: int = 1600) -> list[str]:
    """
    Split a long paragraph into sentence-aware pieces.
    """
    if len(paragraph) <= max_chars:
        return [paragraph]
    
    sentences = re.split(r"(?<=[.!?])\s+", paragraph)
    
    pieces = []
    current = ""
    
    for sentence in sentences:
        candidate = (current + " " + sentence).strip()
        
        if len(candidate) <= max_chars:
            current = candidate
        else:
            if current:
                pieces.append(current)
            current = sentence
    
    if current:
        pieces.append(current)
    
    return pieces


print("Long paragraph splitter ready.")

Long paragraph splitter ready.

In [27]:
def paragraph_aware_chunking(
    paragraphs: list[str],
    min_chunk_chars: int = 600,
    max_chunk_chars: int = 1800,
    overlap_chars: int = 120
) -> list[str]:
    """
    Build chunks by combining paragraphs until the chunk is large enough,
    without exceeding max length too much.
    """
    chunks = []
    current_chunk = ""
    
    for paragraph in paragraphs:
        # If paragraph is too long, split it first
        paragraph_pieces = split_long_paragraph(paragraph, max_chars=max_chunk_chars)
        
        for piece in paragraph_pieces:
            candidate = (current_chunk + "\n\n" + piece).strip() if current_chunk else piece
            
            if len(candidate) <= max_chunk_chars:
                current_chunk = candidate
            else:
                if current_chunk:
                    chunks.append(current_chunk.strip())
                current_chunk = piece
        
        if len(current_chunk) >= min_chunk_chars:
            chunks.append(current_chunk.strip())
            current_chunk = ""
    
    if current_chunk:
        chunks.append(current_chunk.strip())
    
    # Add light overlap, but only at character level for continuity
    overlapped_chunks = []
    
    for i, chunk in enumerate(chunks):
        if i == 0:
            overlapped_chunks.append(chunk)
        else:
            previous_tail = overlapped_chunks[-1][-overlap_chars:]
            overlapped_chunks.append((previous_tail + "\n\n" + chunk).strip())
    
    return overlapped_chunks


paragraph_chunks = paragraph_aware_chunking(paragraphs)

print("Paragraph-aware chunks:", len(paragraph_chunks))
print("First chunk length:", len(paragraph_chunks[0]))
print(paragraph_chunks[0][:1200])

Paragraph-aware chunks: 90
First chunk length: 1045
About this guide This guide is for Australian financial services (AFS) licensees, unlicensed product issuers, unlicensed secondary sellers, trustees of regulated superannuation funds (other than self-managed superannuation funds (SMSFs)), trustees of approved deposit funds, retirement savings account providers, Australian credit licensees (credit licensees) and unlicensed carried over instrument lenders (unlicensed COI lenders). The standards and requirements highlighted in this guide are enforceable. It explains what these financial firms must do to have an internal dispute resolution (IDR) system in place that meets ASIC’s standards and requirements. Note: This guide comes into effect on 5 October 2021. For complaints received by financial firms before that date, Regulatory Guide 165 Licensing: Internal and external dispute resolution (RG 165) applies. We will withdraw RG 165 on 5 October 2022. This guide should be read in conjunction with Regulatory Guide 267 Oversight of the Australian Financial Complaints Authority (RG 267).

In [28]:
for i, chunk in enumerate(paragraph_chunks[:8]):
    print(f"\n--- Paragraph-aware Chunk {i} ---")
    print("Length:", len(chunk))
    print(chunk[:1200])

--- Paragraph-aware Chunk 0 ---
Length: 1045
About this guide This guide is for Australian financial services (AFS) licensees, unlicensed product issuers, unlicensed secondary sellers, trustees of regulated superannuation funds (other than self-managed superannuation funds (SMSFs)), trustees of approved deposit funds, retirement savings account providers, Australian credit licensees (credit licensees) and unlicensed carried over instrument lenders (unlicensed COI lenders). The standards and requirements highlighted in this guide are enforceable. It explains what these financial firms must do to have an internal dispute resolution (IDR) system in place that meets ASIC’s standards and requirements. Note: This guide comes into effect on 5 October 2021. For complaints received by financial firms before that date, Regulatory Guide 165 Licensing: Internal and external dispute resolution (RG 165) applies. We will withdraw RG 165 on 5 October 2022. This guide should be read in conjunction with Regulatory Guide 267 Oversight of the Australian Financial Complaints Authority (RG 267).

--- Paragraph-aware Chunk 1 ---
Length: 1675
ld be read in conjunction with Regulatory Guide 267 Oversight of the Australian Financial Complaints Authority (RG 267).

About ASIC regulatory documents In administering legislation ASIC issues the following types of regulatory documents. Consultation papers: seek feedback from stakeholders on matters ASIC is considering, such as proposed relief or proposed regulatory guidance. Regulatory guides: give guidance to regulated entities by:  explaining when and how ASIC will exercise specific powers under legislation (primarily the Corporations Act)  explaining how ASIC interprets the law  describing the principles underlying ASIC’s approach  giving practical guidance (e.g. describing the steps of a process such as applying for a licence or giving practical examples of how regulated entities may decide to meet their obligations). Information sheets: provide concise guidance on a specific process or compliance issue or an overview of detailed guidance. Reports: describe ASIC compliance or relief activity or the results of a research project. Document history This guide was issued in and is based on legislation and regulations as at the date of issue. Previous versions:  Superseded

--- Paragraph-aware Chunk 2 ---
Length: 1671
Credit Act, SIS Act and other applicable laws apply to you, as it is your responsibility to determine your obligations.

A Overview Key points Financial firms must have a dispute resolution system that consists of: • an internal dispute resolution (IDR) procedure that meets the standards or requirements made or approved by ASIC; and • membership of the Australian Financial Complaints Authority (AFCA). Our dispute resolution standards and requirements are set out in: • this guide, which sets out how financial firms must meet their obligations; and • Regulatory Guide 267 Oversight of the Australian Financial Complaints Authority (RG 267), which sets out how we will administer ASIC’s powers and perform our oversight role over AFCA. We must, when considering whether to make or approve standards or requirements relating to IDR, take into account: • Australian Standard AS/NZS 10002:2014 Guidelines for complaint management in organizations (AS/NZS 10002:2014); and • any other matter we consider relevant. The standards and requirements highlighted in this guide are enforceable. This regulatory guide updates our previous IDR standards and requirements to: • give effect to the reforms introd

--- Paragraph-aware Chunk 3 ---
Length: 714
ndling set out in AS/NZS 10002:2014; and • refine our requirements in some key areas based on our regulatory experience.

Financial services dispute resolution framework RG 271.1 Financial firms must have in place a dispute resolution system that consists of: (a) an IDR procedure that complies with standards and requirements made or approved by ASIC; and (b) membership of AFCA. Note 1: See s912A(1)(g) and 1017G(1) of the Corporations Act 2001 (Corporations Act), s47(1)(h) and (i) of the National Consumer Credit Protection Act 2009 (National Credit Act), s101(1) and (1A) of the Superannuation Industry (Supervision) Act 1993 (SIS Act), and s47(1) and (2) of the Retirement Savings Account Act 1997 (RSA Act).

--- Paragraph-aware Chunk 4 ---
Length: 1808
tion Industry (Supervision) Act 1993 (SIS Act), and s47(1) and (2) of the Retirement Savings Account Act 1997 (RSA Act).

Note 2: Unlicensed carried over instrument lenders (unlicensed COI lenders) have IDR obligations, but are not required to be a member of AFCA (see RG 271.3). RG 271.2 Most financial firms also have a requirement to comply with their IDR procedures: see modified s912A(1)(g) and 1017G(1) of the Corporations Act, and modified s47(1)(h) and (i) of the National Credit Act. RG 271.3 A modified regulatory regime applies to some unlicensed credit firms. Credit representatives and exempt special purpose funding entities (exempt SPFEs) (including securitisation bodies) do not have IDR obligations, but must be a member of AFCA. Unlicensed carried over instrument lenders (unlicensed COI lenders) have IDR obligations but are not required to be a member of AFCA. Note: See s64 and 65 of the National Credit Act, and regs 23B and 23C of the National Consumer Credit Protection Regulations 2010 (National Credit Regulations); see also reg 25E of the National Credit Regulations and s47(1)(e) of the National Credit Act (inserted by Sch 2 to the National Credit Regulations). RG 271.4

--- Paragraph-aware Chunk 5 ---
Length: 1375
;  provide a custodial or depository service; or  provide traditional trustee company services (traditional services).

AFS licensees must have a dispute resolution system that consists of:  an IDR procedure that complies with the standards and requirements made or approved by ASIC (set out in this guide) that cover complaints made by retail clients in relation to the financial services provided; and  membership of AFCA. AFS licensees must also comply with their IDR procedure. Note: See s912A(1)(g) of the Corporations Act. Unlicensed product issuers and unlicensed secondary sellers An unlicensed product issuer is an issuer of a financial product who is not an AFS licensee. An unlicensed secondary seller is a person who offers the secondary sale of a financial product under s1012C(5)(b) or (8) of the Corporations Act and who is not an AFS licensee. Unlicensed product issuers and unlicensed secondary sellers are required to have a dispute resolution system that consists of:  an IDR procedure that complies with the standards and requirements made or approved by ASIC (set out in this guide) that cover complaints made by retail clients in relation to the financial services provided

--- Paragraph-aware Chunk 6 ---
Length: 1853
and unlicensed secondary sellers must also comply with their IDR processes. Note: See s1017G(2) of the Corporations Act.

Firm type Description Dispute resolution requirements Superannuation trustees A trustee of a regulated superannuation fund (other than a self-managed superannuation fund (SMSF)), trustee of an approved deposit fund or a retirement savings account (RSA) provider. Superannuation trustees must:  be a member of AFCA; and  have an IDR procedure that complies with the standards and requirements set out in s912A(2)(a)(i) of the Corporations Act. Note 1: See also s101(1)(a)–(c) of the SIS Act. Note 2: However, s101(1)(a)–(c) of the SIS Act does not apply to a trustee if the trustee is required under the Corporations Act to have a dispute resolution system complying with s912A(2) or 1017G(2) of the Act. Australian credit licensees (credit licensees) Credit providers and lessors, including those who are assigned the contractual rights of a credit provider or lessor (which can include debt collectors who purchase a debt from a credit provider or lessor). Credit service providers (such as brokers and other intermediaries), and other (such as debt collectors) who act on be

--- Paragraph-aware Chunk 7 ---
Length: 1006
o engage in specified credit activities on behalf of a credit licensee under s64(2) or 65(2) of the National Credit Act.

The employees and directors of a credit licensee do not need to be formally authorised—they act as representatives of the credit licensee without a specific authorisation. A person can also be authorised as a credit representative by more than one credit licensee. Credit representatives do not need to have IDR processes that meet the standards and requirements made or approved by ASIC. This is because a credit licensee’s IDR process must cover disputes relating to its credit representatives. Most credit representatives are required to be separate members of AFCA: see s64 and 65 of the National Credit Act. However, a person who has been sub- authorised under s65(1) of the National Credit Act and is an employee or director of the body corporate that gave the sub-authorisation does not need to be a separate member of AFCA. Note: See reg 16 of the National Credit Regulations.

In [29]:
chunk_comparison_v3 = pd.DataFrame([
    {
        "method": "recursive_v1",
        "num_chunks": len(recursive_chunks),
        "avg_chunk_chars": round(np.mean([len(c) for c in recursive_chunks]), 1),
        "min_chunk_chars": min(len(c) for c in recursive_chunks),
        "max_chunk_chars": max(len(c) for c in recursive_chunks),
        "manual_quality": "poor - cuts across structure"
    },
    {
        "method": "section_aware",
        "num_chunks": len(section_chunks),
        "avg_chunk_chars": round(np.mean([len(c) for c in section_chunks]), 1),
        "min_chunk_chars": min(len(c) for c in section_chunks),
        "max_chunk_chars": max(len(c) for c in section_chunks),
        "manual_quality": "good candidate for regulatory PDF"
    },
    {
        "method": "semantic_v2",
        "num_chunks": len(semantic_chunks_v2),
        "avg_chunk_chars": round(np.mean([len(c) for c in semantic_chunks_v2]), 1),
        "min_chunk_chars": min(len(c) for c in semantic_chunks_v2),
        "max_chunk_chars": max(len(c) for c in semantic_chunks_v2),
        "manual_quality": "mixed - better than recursive but sometimes too broad"
    },
    {
        "method": "paragraph_aware",
        "num_chunks": len(paragraph_chunks),
        "avg_chunk_chars": round(np.mean([len(c) for c in paragraph_chunks]), 1),
        "min_chunk_chars": min(len(c) for c in paragraph_chunks),
        "max_chunk_chars": max(len(c) for c in paragraph_chunks),
        "manual_quality": "expected strongest for readable retrieval chunks"
    }
])

chunk_comparison_v3

,method,num_chunks,avg_chunk_chars,min_chunk_chars,max_chunk_chars,manual_quality
0,recursive_v1,125,1142.5,223,1351,poor - cuts across structure
1,section_aware,74,1716.8,444,1949,good candidate for regulatory PDF
2,semantic_v2,101,1148.3,452,3162,mixed - better than recursive but sometimes too broad
3,paragraph_aware,90,1389.1,211,1922,expected strongest for readable retrieval chunks

## Method D — RG Paragraph-Aware Chunking

The previous methods produced readable chunks in some places, but still created poor boundaries because PDF text extraction and character-level overlap caused chunks to begin in the middle of words or sentences.

For ASIC RG 271, a better approach is to use the document's own regulatory paragraph structure.

This method splits the text around `RG 271.x` paragraph references, then groups nearby paragraphs into readable retrieval chunks.

The goal is to create chunks that:
- start at meaningful regulatory paragraph boundaries,
- preserve RG paragraph references,
- avoid broken word starts,
- avoid character-level overlap,
- remain useful as standalone RAG context.

In [30]:
import re
import pandas as pd
import numpy as np

def extract_rg_paragraph_blocks(text: str) -> list[dict]:
    """
    Extract blocks starting with RG 271.x references.
    Each block keeps its RG paragraph number and related text.
    """
    pattern = r"(RG\s+271\.\d+[A-Z]?)"
    
    matches = list(re.finditer(pattern, text))
    blocks = []
    
    for i, match in enumerate(matches):
        start = match.start()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        
        rg_ref = match.group(1)
        block_text = text[start:end].strip()
        block_text = re.sub(r"\s+", " ", block_text).strip()
        
        if len(block_text) > 80:
            blocks.append({
                "rg_ref": rg_ref,
                "text": block_text,
                "length": len(block_text)
            })
    
    return blocks


rg_blocks = extract_rg_paragraph_blocks(clean_rg271_text)

print("RG paragraph blocks:", len(rg_blocks))

pd.DataFrame(rg_blocks).head(10)

RG paragraph blocks: 230

,rg_ref,text,length
0,RG 271.1,"RG 271.1 Financial firms must have in place a dispute resolution system that consists of: (a) an IDR procedure that complies with standards and requirements made or approved by ASIC; and (b) membership of AFCA. Note 1: See s912A(1)(g) and 1017G(1) of the Corporations Act 2001 (Corporations Act),...",691
1,RG 271.2,"RG 271.2 Most financial firms also have a requirement to comply with their IDR procedures: see modified s912A(1)(g) and 1017G(1) of the Corporations Act, and modified s47(1)(h) and (i) of the National Credit Act.",212
2,RG 271.3,"RG 271.3 A modified regulatory regime applies to some unlicensed credit firms. Credit representatives and exempt special purpose funding entities (exempt SPFEs) (including securitisation bodies) do not have IDR obligations, but must be a member of AFCA. Unlicensed carried over instrument lenders...",697
3,RG 271.4,RG 271.4 Table 1 sets out the dispute resolution requirements by type of financial firm. Table 1: Legislative dispute resolution requirements by firm type Firm type Description Dispute resolution requirements Australian financial services (AFS) licensees An AFS licensee is a business carrying ou...,10625
4,RG 271.5,"RG 271.5 The objectives of Ch 7 of the Corporations Act are to promote: (a) the confident and informed participation of consumers and investors in the Australian financial system (also an objective of ASIC under s1 of the Australian Securities and Investments Commission Act 2001); (b) fairness, ...",488
5,RG 271.6,"RG 271.6 Within this framework, we are responsible for overseeing the effective operation of the dispute resolution system, which includes setting the standards and requirements for financial firms’ IDR processes and oversight of AFCA.",235
6,RG 271.7,"RG 271.7 We must, when considering whether to make or approve standards or requirements relating to IDR, take into account: (a) AS/NZS 10002:2014; and Note: AS/NZS 10002:2014 is published by SAI Global and available for purchase on their website. It is also available through public libraries acr...",538
7,RG 271.8,"RG 271.8 The standards and requirements set out in ASIC Corporations, Credit and Superannuation (Internal Dispute Resolution) Instrument 2020/98 and highlighted in this guide are enforceable. Other highlighted requirements in this guide reflect existing legal requirements and are also enforceable.",298
8,RG 271.9,RG 271.9 The parts of this guide that we have not highlighted or set out in the instrument are guidance to help financial firms comply with their legal obligations.,164
9,RG 271.10,"RG 271.10 We may vary or revoke: (a) a standard or requirement that we have made for IDR; and (b) the operation of a standard or requirement that we have approved in its application to IDR. Note: See regs 7.6.02(2) and 7.9.77(2) of the Corporations Regulations, and reg 10(2) and item 2.20 of Sch...",334

In [31]:
for i, block in enumerate(rg_blocks[:8]):
    print(f"\n--- RG Block {i} | {block['rg_ref']} | Length: {block['length']} ---")
    print(block["text"][:1000])

--- RG Block 0 | RG 271.1 | Length: 691 ---
RG 271.1 Financial firms must have in place a dispute resolution system that consists of: (a) an IDR procedure that complies with standards and requirements made or approved by ASIC; and (b) membership of AFCA. Note 1: See s912A(1)(g) and 1017G(1) of the Corporations Act 2001 (Corporations Act), s47(1)(h) and (i) of the National Consumer Credit Protection Act 2009 (National Credit Act), s101(1) and (1A) of the Superannuation Industry (Supervision) Act 1993 (SIS Act), and s47(1) and (2) of the Retirement Savings Account Act 1997 (RSA Act). Note 2: Unlicensed carried over instrument lenders (unlicensed COI lenders) have IDR obligations, but are not required to be a member of AFCA (see

--- RG Block 1 | RG 271.2 | Length: 212 ---
RG 271.2 Most financial firms also have a requirement to comply with their IDR procedures: see modified s912A(1)(g) and 1017G(1) of the Corporations Act, and modified s47(1)(h) and (i) of the National Credit Act.

--- RG Block 2 | RG 271.3 | Length: 697 ---
RG 271.3 A modified regulatory regime applies to some unlicensed credit firms. Credit representatives and exempt special purpose funding entities (exempt SPFEs) (including securitisation bodies) do not have IDR obligations, but must be a member of AFCA. Unlicensed carried over instrument lenders (unlicensed COI lenders) have IDR obligations but are not required to be a member of AFCA. Note: See s64 and 65 of the National Credit Act, and regs 23B and 23C of the National Consumer Credit Protection Regulations 2010 (National Credit Regulations); see also reg 25E of the National Credit Regulations and s47(1)(e) of the National Credit Act (inserted by Sch 2 to the National Credit Regulations).

--- RG Block 3 | RG 271.4 | Length: 10625 ---
RG 271.4 Table 1 sets out the dispute resolution requirements by type of financial firm. Table 1: Legislative dispute resolution requirements by firm type Firm type Description Dispute resolution requirements Australian financial services (AFS) licensees An AFS licensee is a business carrying out financial services. This includes businesses that:  provide financial product advice to clients;  deal in a financial product;  make a market for a financial product;  operate a registered scheme;  provide a custodial or depository service; or  provide traditional trustee company services (traditional services). AFS licensees must have a dispute resolution system that consists of:  an IDR procedure that complies with the standards and requirements made or approved by ASIC (set out in this guide) that cover complaints made by retail clients in relation to the financial services provided; and  membership of AFCA. AFS licensees must also comply with their IDR procedure. Note: See s912A(1)

--- RG Block 4 | RG 271.5 | Length: 488 ---
RG 271.5 The objectives of Ch 7 of the Corporations Act are to promote: (a) the confident and informed participation of consumers and investors in the Australian financial system (also an objective of ASIC under s1 of the Australian Securities and Investments Commission Act 2001); (b) fairness, honesty and professionalism by those who provide financial services; (c) fair, orderly and transparent markets; and (d) the reduction of systemic risks. Note: See s760A of the Corporations Act

--- RG Block 5 | RG 271.6 | Length: 235 ---
RG 271.6 Within this framework, we are responsible for overseeing the effective operation of the dispute resolution system, which includes setting the standards and requirements for financial firms’ IDR processes and oversight of AFCA.

--- RG Block 6 | RG 271.7 | Length: 538 ---
RG 271.7 We must, when considering whether to make or approve standards or requirements relating to IDR, take into account: (a) AS/NZS 10002:2014; and Note: AS/NZS 10002:2014 is published by SAI Global and available for purchase on their website. It is also available through public libraries across Australia. (b) any other matter we consider relevant. Note: See regs 7.6.02(1)(a) and 7.9.77(1)(a) of the Corporations Regulations 2001 (Corporations Regulations) and reg 10(1)(a) and item 2.20 of Sch 2 to the National Credit Regulations.

--- RG Block 7 | RG 271.8 | Length: 298 ---
RG 271.8 The standards and requirements set out in ASIC Corporations, Credit and Superannuation (Internal Dispute Resolution) Instrument 2020/98 and highlighted in this guide are enforceable. Other highlighted requirements in this guide reflect existing legal requirements and are also enforceable.

In [32]:
def build_rg_aware_chunks(
    rg_blocks: list[dict],
    min_chunk_chars: int = 700,
    max_chunk_chars: int = 1800
) -> list[dict]:
    """
    Combine RG paragraph blocks into retrieval chunks.
    No character-level overlap is used to avoid broken starts.
    """
    chunks = []
    current_texts = []
    current_refs = []
    current_length = 0
    
    for block in rg_blocks:
        block_text = block["text"]
        block_ref = block["rg_ref"]
        
        candidate_length = current_length + len(block_text) + 2
        
        if candidate_length <= max_chunk_chars:
            current_texts.append(block_text)
            current_refs.append(block_ref)
            current_length = candidate_length
        else:
            if current_texts:
                chunks.append({
                    "chunk_id": len(chunks),
                    "method": "rg_paragraph_aware",
                    "rg_refs": current_refs.copy(),
                    "text": "\n\n".join(current_texts),
                    "length": len("\n\n".join(current_texts))
                })
            
            current_texts = [block_text]
            current_refs = [block_ref]
            current_length = len(block_text)
        
        if current_length >= min_chunk_chars:
            chunks.append({
                "chunk_id": len(chunks),
                "method": "rg_paragraph_aware",
                "rg_refs": current_refs.copy(),
                "text": "\n\n".join(current_texts),
                "length": len("\n\n".join(current_texts))
            })
            current_texts = []
            current_refs = []
            current_length = 0
    
    if current_texts:
        chunks.append({
            "chunk_id": len(chunks),
            "method": "rg_paragraph_aware",
            "rg_refs": current_refs.copy(),
            "text": "\n\n".join(current_texts),
            "length": len("\n\n".join(current_texts))
        })
    
    return chunks


rg_chunks = build_rg_aware_chunks(rg_blocks)

print("RG-aware chunks:", len(rg_chunks))

rg_chunks_df = pd.DataFrame(rg_chunks)
rg_chunks_df.head()

RG-aware chunks: 88

,chunk_id,method,rg_refs,text,length
0,0,rg_paragraph_aware,"[RG 271.1, RG 271.2]","RG 271.1 Financial firms must have in place a dispute resolution system that consists of: (a) an IDR procedure that complies with standards and requirements made or approved by ASIC; and (b) membership of AFCA. Note 1: See s912A(1)(g) and 1017G(1) of the Corporations Act 2001 (Corporations Act),...",905
1,1,rg_paragraph_aware,[RG 271.3],"RG 271.3 A modified regulatory regime applies to some unlicensed credit firms. Credit representatives and exempt special purpose funding entities (exempt SPFEs) (including securitisation bodies) do not have IDR obligations, but must be a member of AFCA. Unlicensed carried over instrument lenders...",697
2,2,rg_paragraph_aware,[RG 271.4],RG 271.4 Table 1 sets out the dispute resolution requirements by type of financial firm. Table 1: Legislative dispute resolution requirements by firm type Firm type Description Dispute resolution requirements Australian financial services (AFS) licensees An AFS licensee is a business carrying ou...,10625
3,3,rg_paragraph_aware,"[RG 271.5, RG 271.6]","RG 271.5 The objectives of Ch 7 of the Corporations Act are to promote: (a) the confident and informed participation of consumers and investors in the Australian financial system (also an objective of ASIC under s1 of the Australian Securities and Investments Commission Act 2001); (b) fairness, ...",725
4,4,rg_paragraph_aware,"[RG 271.7, RG 271.8]","RG 271.7 We must, when considering whether to make or approve standards or requirements relating to IDR, take into account: (a) AS/NZS 10002:2014; and Note: AS/NZS 10002:2014 is published by SAI Global and available for purchase on their website. It is also available through public libraries acr...",838

In [33]:
for i, row in rg_chunks_df.head(10).iterrows():
    print(f"\n--- RG-aware Chunk {row['chunk_id']} ---")
    print("RG refs:", row["rg_refs"])
    print("Length:", row["length"])
    print(row["text"][:1200])

--- RG-aware Chunk 0 ---
RG refs: ['RG 271.1', 'RG 271.2']
Length: 905
RG 271.1 Financial firms must have in place a dispute resolution system that consists of: (a) an IDR procedure that complies with standards and requirements made or approved by ASIC; and (b) membership of AFCA. Note 1: See s912A(1)(g) and 1017G(1) of the Corporations Act 2001 (Corporations Act), s47(1)(h) and (i) of the National Consumer Credit Protection Act 2009 (National Credit Act), s101(1) and (1A) of the Superannuation Industry (Supervision) Act 1993 (SIS Act), and s47(1) and (2) of the Retirement Savings Account Act 1997 (RSA Act). Note 2: Unlicensed carried over instrument lenders (unlicensed COI lenders) have IDR obligations, but are not required to be a member of AFCA (see

RG 271.2 Most financial firms also have a requirement to comply with their IDR procedures: see modified s912A(1)(g) and 1017G(1) of the Corporations Act, and modified s47(1)(h) and (i) of the National Credit Act.

--- RG-aware Chunk 1 ---
RG refs: ['RG 271.3']
Length: 697
RG 271.3 A modified regulatory regime applies to some unlicensed credit firms. Credit representatives and exempt special purpose funding entities (exempt SPFEs) (including securitisation bodies) do not have IDR obligations, but must be a member of AFCA. Unlicensed carried over instrument lenders (unlicensed COI lenders) have IDR obligations but are not required to be a member of AFCA. Note: See s64 and 65 of the National Credit Act, and regs 23B and 23C of the National Consumer Credit Protection Regulations 2010 (National Credit Regulations); see also reg 25E of the National Credit Regulations and s47(1)(e) of the National Credit Act (inserted by Sch 2 to the National Credit Regulations).

--- RG-aware Chunk 2 ---
RG refs: ['RG 271.4']
Length: 10625
RG 271.4 Table 1 sets out the dispute resolution requirements by type of financial firm. Table 1: Legislative dispute resolution requirements by firm type Firm type Description Dispute resolution requirements Australian financial services (AFS) licensees An AFS licensee is a business carrying out financial services. This includes businesses that:  provide financial product advice to clients;  deal in a financial product;  make a market for a financial product;  operate a registered scheme;  provide a custodial or depository service; or  provide traditional trustee company services (traditional services). AFS licensees must have a dispute resolution system that consists of:  an IDR procedure that complies with the standards and requirements made or approved by ASIC (set out in this guide) that cover complaints made by retail clients in relation to the financial services provided; and  membership of AFCA. AFS licensees must also comply with their IDR procedure. Note: See s912A(1)(g) of the Corporations Act. Unlicensed product issuers and unlicensed secondary sellers An unlicensed product issuer is an issuer of a financial product who is not an AFS licensee. An unlicensed seco

--- RG-aware Chunk 3 ---
RG refs: ['RG 271.5', 'RG 271.6']
Length: 725
RG 271.5 The objectives of Ch 7 of the Corporations Act are to promote: (a) the confident and informed participation of consumers and investors in the Australian financial system (also an objective of ASIC under s1 of the Australian Securities and Investments Commission Act 2001); (b) fairness, honesty and professionalism by those who provide financial services; (c) fair, orderly and transparent markets; and (d) the reduction of systemic risks. Note: See s760A of the Corporations Act

RG 271.6 Within this framework, we are responsible for overseeing the effective operation of the dispute resolution system, which includes setting the standards and requirements for financial firms’ IDR processes and oversight of AFCA.

--- RG-aware Chunk 4 ---
RG refs: ['RG 271.7', 'RG 271.8']
Length: 838
RG 271.7 We must, when considering whether to make or approve standards or requirements relating to IDR, take into account: (a) AS/NZS 10002:2014; and Note: AS/NZS 10002:2014 is published by SAI Global and available for purchase on their website. It is also available through public libraries across Australia. (b) any other matter we consider relevant. Note: See regs 7.6.02(1)(a) and 7.9.77(1)(a) of the Corporations Regulations 2001 (Corporations Regulations) and reg 10(1)(a) and item 2.20 of Sch 2 to the National Credit Regulations.

RG 271.8 The standards and requirements set out in ASIC Corporations, Credit and Superannuation (Internal Dispute Resolution) Instrument 2020/98 and highlighted in this guide are enforceable. Other highlighted requirements in this guide reflect existing legal requirements and are also enforceable.

--- RG-aware Chunk 5 ---
RG refs: ['RG 271.9', 'RG 271.10', 'RG 271.11', 'RG 271.12']
Length: 1025
RG 271.9 The parts of this guide that we have not highlighted or set out in the instrument are guidance to help financial firms comply with their legal obligations.

RG 271.10 We may vary or revoke: (a) a standard or requirement that we have made for IDR; and (b) the operation of a standard or requirement that we have approved in its application to IDR. Note: See regs 7.6.02(2) and 7.9.77(2) of the Corporations Regulations, and reg 10(2) and item 2.20 of Sch 2 to the National Credit Regulations.

RG 271.11 We have made the requirements in this guide to meet our statutory obligations and, in doing so, promote fair consumer outcomes. The importance of IDR

RG 271.12 Consumer and small business access to fair, timely and effective dispute resolution is an essential part of the financial services consumer protection framework. It is consistent with ASIC’s function of promoting consumer protection in the Australian financial system. Note: See s12A(2) of the Australian Securities and Investments Commission Act 2001.

--- RG-aware Chunk 6 ---
RG refs: ['RG 271.13', 'RG 271.14', 'RG 271.15']
Length: 1319
RG 271.13 As the first step in the financial dispute resolution framework, IDR provides an opportunity for redress to millions of consumers and small businesses each year.

RG 271.14 The Ramsay Review’s Final report: Review of the financial system external dispute resolution and complaints framework (Ramsay Review final report) stated at p. 189: Effective IDR benefits both firms and consumers. IDR is an important element of financial firms’ overall relationship with their customers and is the primary avenue for aggrieved consumers to seek redress. Pressure on [external dispute resolution] is reduced when complaints are resolved directly between firms and their customers.

RG 271.15 We encourage all financial firms to cultivate an organisational culture that welcomes feedback and values complaints. A positive complaint management culture can produce beneficial outcomes for both consumers and firms, including: (a) the opportunity to resolve complaints quickly and directly; (b) the promotion of trusted relationships between the parties; (c) improved levels of consumer confidence and satisfaction; (d) greater understanding of the key drivers of complaints; (e) the ability to identify e

--- RG-aware Chunk 7 ---
RG refs: ['RG 271.16', 'RG 271.17']
Length: 1050
RG 271.16 To develop and maintain a positive complaint management culture, financial firms should have a robust IDR process, including all procedures, documents, policies, resources, governance and arrangements in place to manage complaints.

RG 271.17 Many firms have addressed the foundational aspects of their IDR process. However, we consider more progress can be made in key areas, including: (a) achieving organisation-wide understanding of the definition of ‘complaint’ and the types of matters that must be dealt with in a firm’s IDR process; (b) increasing the capture, tracking, analysis and reporting of complaint data; (c) improving timeliness and efficiency; (d) enhancing the quality of written communications and IDR responses; (e) strengthening complaint management skills; (f) fostering organisation-wide accountability for complaint management; and (g) leveraging the power of technology and data analytics to improve both the IDR process and the products and services offered by financial firms. Application of the IDR requirements

--- RG-aware Chunk 8 ---
RG refs: ['RG 271.18', 'RG 271.19', 'RG 271.20', 'RG 271.21']
Length: 734
RG 271.18 The IDR requirements set out in this guide apply to any expression of dissatisfaction made by a consumer that meets the definition of ‘complaint’ set out in in AS/NZS 10002:2014: see

RG 271.19 We have provided guidance on the types of consumer (including small businesses) that financial firms’ IDR processes should cover: see

RG 271.20 Financial firms may tailor their IDR process to suit the nature, scale and complexity of their business. We have provided guidance on the issues firms should consider when tailoring their process at

RG 271.21 Financial firms may also outsource part or all of their IDR process. For guidance on the responsibilities that still apply to firms that have outsourced their IDR process, see

--- RG-aware Chunk 9 ---
RG refs: ['RG 271.22', 'RG 271.106', 'RG 271.116', 'RG 271.23', 'RG 271.24']
Length: 1190
RG 271.22 This guide sets out: (a) the definition of ‘complaint’ set out in AS/NZS 10002:2014 (see

RG 271.106); (d) our requirements for how financial firms’ IDR processes and procedures will interact with AFCA (see

RG 271.116); (e) the requirements for identifying and escalating systemic issues (see Section D); and (f) our IDR standards (see Section E).

RG 271.23 There are many different kinds of financial firms providing a diverse range of financial products and services. We do not take a ‘one size fits all’ approach to regulation. What firms need to do to comply with their IDR obligations will vary according to the nature, scale and complexity of their business.

RG 271.24 When reviewing or establishing an IDR process, a financial firm should take into account: (a) the size of their business and the number of people in the organisation; (b) the products and services offered and the volume and size of transactions the firm is responsible for; (c) the nature of their customer base; (d) the diversity and structure of their operations (including the extent to which the IDR function is outsourced); and (e) the likely number and complexity of complaints. Transition period

## Method E — Agentic Chunking with LLM

The previous chunking methods were not satisfactory for this regulatory PDF because they still produced chunks with broken starts, weak paragraph boundaries, or overly broad context.

This method uses an LLM to create standalone, meaning-preserving regulatory chunks.

The chunking rules are:
- Do not split words.
- Do not split sentences.
- Preserve headings and RG references.
- Keep each chunk self-contained.
- Split long tables or clauses into meaningful subparts.
- Return structured JSON for downstream RAG ingestion.

In [34]:
from openai import OpenAI
from dotenv import load_dotenv
import os
import json
import pandas as pd
import re
from pathlib import Path

# Find .env by walking up from the current working directory.
env_path = None
for base in [Path.cwd(), *Path.cwd().parents]:
    candidate = base / ".env"
    if candidate.exists():
        env_path = candidate
        break

if env_path:
    load_dotenv(env_path)

api_key = os.getenv("OPENAI_API_KEY")

if not api_key:
    raise RuntimeError(
        f"OPENAI_API_KEY not found. Checked current working directory chain starting from: {Path.cwd()}"
    )

client = OpenAI(api_key=api_key)

print("OpenAI client created.")
print("Loaded .env from:", env_path)
print("API key available:", bool(api_key))

OpenAI client created.
Loaded .env from: /Users/osmanorka/Complaint-Intelligence-Platform-PII-Safe-Classification-RAG-Assistant-for-Financial-Complaints/complaint-intelligence-platform/.env
API key available: True

In [35]:
AGENTIC_CHUNKING_SYSTEM_PROMPT = """
You are an expert regulatory document chunking assistant.

Your task is to split ASIC RG 271 text into high-quality retrieval chunks for a RAG system.

Rules:
1. Do not split words.
2. Do not split sentences.
3. Preserve headings, section names, RG references, and legal references.
4. Each chunk must be understandable on its own.
5. If a table is too long, split it by logical row groups, not by character count.
6. Keep chunks focused on one topic or regulatory requirement.
7. Do not rewrite the meaning of the text.
8. Do not add legal advice.
9. Remove obvious PDF noise such as page numbers, repeated headers, and copyright footers.
10. Return valid JSON only.

Output JSON format:
{
  "chunks": [
    {
      "title": "short descriptive title",
      "rg_refs": ["RG 271.1"],
      "chunk_type": "overview | requirement | definition | timeframe | table | standard | systemic_issue | other",
      "text": "clean standalone chunk text"
    }
  ]
}
"""

In [36]:
test_agentic_input = rg_chunks_df.loc[0:2, "text"].str.cat(sep="\n\n")

print("Input characters:", len(test_agentic_input))
print(test_agentic_input[:2000])

Input characters: 12231
RG 271.1 Financial firms must have in place a dispute resolution system that consists of: (a) an IDR procedure that complies with standards and requirements made or approved by ASIC; and (b) membership of AFCA. Note 1: See s912A(1)(g) and 1017G(1) of the Corporations Act 2001 (Corporations Act), s47(1)(h) and (i) of the National Consumer Credit Protection Act 2009 (National Credit Act), s101(1) and (1A) of the Superannuation Industry (Supervision) Act 1993 (SIS Act), and s47(1) and (2) of the Retirement Savings Account Act 1997 (RSA Act). Note 2: Unlicensed carried over instrument lenders (unlicensed COI lenders) have IDR obligations, but are not required to be a member of AFCA (see

RG 271.2 Most financial firms also have a requirement to comply with their IDR procedures: see modified s912A(1)(g) and 1017G(1) of the Corporations Act, and modified s47(1)(h) and (i) of the National Credit Act.

RG 271.3 A modified regulatory regime applies to some unlicensed credit firms. Credit representatives and exempt special purpose funding entities (exempt SPFEs) (including securitisation bodies) do not have IDR obligations, but must be a member of AFCA. Unlicensed carried over instrument lenders (unlicensed COI lenders) have IDR obligations but are not required to be a member of AFCA. Note: See s64 and 65 of the National Credit Act, and regs 23B and 23C of the National Consumer Credit Protection Regulations 2010 (National Credit Regulations); see also reg 25E of the National Credit Regulations and s47(1)(e) of the National Credit Act (inserted by Sch 2 to the National Credit Regulations).

RG 271.4 Table 1 sets out the dispute resolution requirements by type of financial firm. Table 1: Legislative dispute resolution requirements by firm type Firm type Description Dispute resolution requirements Australian financial services (AFS) licensees An AFS licensee is a business carrying out financial services. This includes businesses that:  provide financial product advice to clients

In [37]:
def agentic_chunk_text(text: str, model: str = "gpt-4.1-mini") -> dict:
    response = client.chat.completions.create(
        model=model,
        temperature=0,
        messages=[
            {
                "role": "system",
                "content": AGENTIC_CHUNKING_SYSTEM_PROMPT
            },
            {
                "role": "user",
                "content": f"Chunk the following ASIC RG 271 text:\n\n{text}"
            }
        ],
        response_format={"type": "json_object"}
    )
    
    return json.loads(response.choices[0].message.content)


agentic_result = agentic_chunk_text(test_agentic_input)

agentic_result

{'chunks': [{'title': 'Overview of dispute resolution system requirements',
   'rg_refs': ['RG 271.1'],
   'chunk_type': 'requirement',
   'text': 'Financial firms must have in place a dispute resolution system that consists of: (a) an IDR procedure that complies with standards and requirements made or approved by ASIC; and (b) membership of AFCA. Note 1: See s912A(1)(g) and 1017G(1) of the Corporations Act 2001 (Corporations Act), s47(1)(h) and (i) of the National Consumer Credit Protection Act 2009 (National Credit Act), s101(1) and (1A) of the Superannuation Industry (Supervision) Act 1993 (SIS Act), and s47(1) and (2) of the Retirement Savings Account Act 1997 (RSA Act). Note 2: Unlicensed carried over instrument lenders (unlicensed COI lenders) have IDR obligations, but are not required to be a member of AFCA.'},
  {'title': 'Compliance with IDR procedures by financial firms',
   'rg_refs': ['RG 271.2'],
   'chunk_type': 'requirement',
   'text': 'Most financial firms also have a requirement to comply with their IDR procedures: see modified s912A(1)(g) and 1017G(1) of the Corporations Act, and modified s47(1)(h) and (i) of the National Credit Act.'},
  {'title': 'Modified regulatory regime for unlicensed credit firms',
   'rg_refs': ['RG 271.3'],
   'chunk_type': 'requirement',
   'text': 'A modified regulatory regime applies to some unlicensed credit firms. Credit representatives and exempt special purpose funding entities (exempt SPFEs) (including securitisation bodies) do not have IDR obligations, but must be a member of AFCA. Unlicensed carried over instrument lenders (unlicensed COI lenders) have IDR obligations but are not required to be a member of AFCA. Note: See s64 and 65 of the National Credit Act, and regs 23B and 23C of the National Consumer Credit Protection Regulations 2010 (National Credit Regulations); see also reg 25E of the National Credit Regulations and s47(1)(e) of the National Credit Act (inserted by Sch 2 to the National Credit Regulations).'},
  {'title': 'Dispute resolution requirements by firm type - Part 1',
   'rg_refs': ['RG 271.4'],
   'chunk_type': 'table',
   'text': 'Table 1 sets out the dispute resolution requirements by type of financial firm.\n\nFirm type: Australian financial services (AFS) licensees\nDescription: An AFS licensee is a business carrying out financial services. This includes businesses that: provide financial product advice to clients; deal in a financial product; make a market for a financial product; operate a registered scheme; provide a custodial or depository service; or provide traditional trustee company services (traditional services).\nDispute resolution requirements: AFS licensees must have a dispute resolution system that consists of: an IDR procedure that complies with the standards and requirements made or approved by ASIC (set out in this guide) that cover complaints made by retail clients in relation to the financial services provided; and membership of AFCA. AFS licensees must also comply with their IDR procedure. Note: See s912A(1)(g) of the Corporations Act.\n\nFirm type: Unlicensed product issuers and unlicensed secondary sellers\nDescription: An unlicensed product issuer is an issuer of a financial product who is not an AFS licensee. An unlicensed secondary seller is a person who offers the secondary sale of a financial product under s1012C(5)(b) or (8) of the Corporations Act and who is not an AFS licensee.\nDispute resolution requirements: Unlicensed product issuers and unlicensed secondary sellers are required to have a dispute resolution system that consists of: an IDR procedure that complies with the standards and requirements made or approved by ASIC (set out in this guide) that cover complaints made by retail clients in relation to the financial services provided; and membership of AFCA. Unlicensed product issuers and unlicensed secondary sellers must also comply with their IDR processes. Note: See s1017G(2) of the Corporations Act.'},
  {'title': 'Dispute resolution requirements by firm type - Part 2',
   'rg_refs': ['RG 271.4'],
   'chunk_type': 'table',
   'text': 'Firm type: Superannuation trustees\nDescription: A trustee of a regulated superannuation fund (other than a self-managed superannuation fund (SMSF)), trustee of an approved deposit fund or a retirement savings account (RSA) provider.\nDispute resolution requirements: Superannuation trustees must: be a member of AFCA; and have an IDR procedure that complies with the standards and requirements set out in s912A(2)(a)(i) of the Corporations Act. Note 1: See also s101(1)(a)–(c) of the SIS Act. Note 2: However, s101(1)(a)–(c) of the SIS Act does not apply to a trustee if the trustee is required under the Corporations Act to have a dispute resolution system complying with s912A(2) or 1017G(2) of the Act.\n\nFirm type: Australian credit licensees (credit licensees)\nDescription: Credit providers and lessors, including those who are assigned the contractual rights of a credit provider or lessor (which can include debt collectors who purchase a debt from a credit provider or lessor). Credit service providers (such as brokers and other intermediaries), and others (such as debt collectors) who act on behalf of the credit provider or lessor.\nDispute resolution requirements: Credit licensees are required to have a dispute resolution system that consists of: an IDR procedure that complies with the standards and requirements made or approved by ASIC (set out in this guide) that cover disputes relating to credit activities they and their representatives engage in; and membership of AFCA. Credit licensees must also comply with their IDR procedures. Note: See s47 of the National Credit Act.'},
  {'title': 'Dispute resolution requirements by firm type - Part 3',
   'rg_refs': ['RG 271.4'],
   'chunk_type': 'table',
   'text': 'Firm type: Credit representatives\nDescription: A credit representative is a person authorised to engage in specified credit activities on behalf of a credit licensee under s64(2) or 65(2) of the National Credit Act. The employees and directors of a credit licensee do not need to be formally authorised—they act as representatives of the credit licensee without a specific authorisation. A person can also be authorised as a credit representative by more than one credit licensee.\nDispute resolution requirements: Credit representatives do not need to have IDR processes that meet the standards and requirements made or approved by ASIC. This is because a credit licensee’s IDR process must cover disputes relating to its credit representatives. Most credit representatives are required to be separate members of AFCA: see s64 and 65 of the National Credit Act. However, a person who has been sub-authorised under s65(1) of the National Credit Act and is an employee or director of the body corporate that gave the sub-authorisation does not need to be a separate member of AFCA. Note: See reg 16 of the National Credit Regulations.'},
  {'title': 'Dispute resolution requirements by firm type - Part 4',
   'rg_refs': ['RG 271.4'],
   'chunk_type': 'table',
   'text': 'Firm type: Unlicensed COI lenders (including prescribed unlicensed COI lenders)\nDescription: A ‘carried over instrument’ is a contract or other instrument that was made and in force, and to which an old Credit Code applied immediately before 1 July 2010 (see s4(1) of the National Consumer Credit Protection (Transitional and Consequential Provisions) Act 2009). Unlicensed COI lenders are credit providers or lessors who only have a closed pool of carried over instruments and have chosen not to obtain a credit licence (or to restrict their activities to their carried over instruments, and subsequently cancel their credit licence).\nNote: A ‘prescribed unlicensed COI lender’ is an unlicensed COI lender who fails to meet certain probity requirements and who has restrictions placed on their conduct in relation to their carried over instruments. A prescribed unlicensed COI lender must not engage in credit activities with respect to their carried over instruments (other than the activities engaged in solely by being the credit provider or lessor). They must instead appoint a credit licensee to act as a ‘representative’ to engage in credit activities on their behalf with respect to their carried over instruments.\nDispute resolution requirements: Unlicensed COI lenders (including prescribed unlicensed COI lenders): must have an IDR procedure that complies with the standards and requirements made or approved by ASIC (set out in this guide) that cover complaints in relation to the credit activities they engage in with respect to their carried over instruments; and may choose to join AFCA. Unlicensed COI lenders must also comply with their IDR procedure.\nNote 1: Details of the obligations of unlicensed COI lenders are set out in Information Sheet 110 Lenders with carried over instruments (INFO 110), Regulatory Guide 205 Credit licensing: Credit conduct obligations (RG 205), Regulatory Guide 206 Credit licensing: Competence and training (RG 206) and Regulatory Guide 207 Credit licensing: Financial requirements (RG 207).\nNote 2: A prescribed unlicensed COI lender may arrange for their credit licensee’s dispute resolution system to cover complaints in relation to their carried over instruments. However, the prescribed unlicensed COI lender remains responsible for ensuring that the requirements and standards set out in Sections C–D are met.\nUnlicensed COI lenders who choose not to join AFCA must keep a register of each of the following: complaints relating to their carried over instruments; hardship notices made under s72 of the National Credit Code (at Sch 1 to the National Credit Act); and requests for postponement of enforcement proceedings under s94 of the National Credit Code.\nNote 1: Unlicensed COI lenders that make arrangements for a third-party provider or their representative’s dispute resolution system to cover complaints relating to their carried over instruments, and that are not a member of AFCA, are still required to meet these register requirements.\nNote 2: See s47(1A) of the National Credit Act (inserted by Sch 2 to the National Credit Regulations) for details of the information the registers must include.'},
  {'title': 'Dispute resolution requirements by firm type - Part 5',
   'rg_refs': ['RG 271.4'],
   'chunk_type': 'table',
   'text': 'Firm type: Exempt SPFEs\nDescription: Special purpose funding entities (SPFEs) include securitisation entities and fundraising special purpose entities that make (or buy) loans or leases and repackage them as investment products to sell to investors. Note: See the definition of ‘special purpose funding’ entity in s5 of the National Credit Act (inserted by Sch 3 to the National Credit Regulations). SPFEs can either operate under a credit licence or as exempt SPFEs: see the licensing exemption in regs 23B and 23C of the National Credit Regulations. Note: See the definition of ‘exempt special purpose funding entity’ in reg 3 of the National Credit Regulations.\nDispute resolution requirements: Exempt SPFEs may rely on a licensing exemption: see regs 23B and 23C of the National Credit Regulations. If they do, they must: enter into a servicing agreement with a credit licensee under which that licensee acts on their behalf; and be a member of AFCA. Exempt SPFEs do not have any IDR requirements. We expect that the credit licensee’s IDR process will cover complaints about both: credit activities engaged in by the licensee under a servicing agreement; and conduct of the exempt SPFE (including where changes are sought to the terms of the contract—for example, on the basis of hardship or because the contract was unsuitable or unjust).\n\nFirm type: Credit licensees acting on behalf of exempt SPFEs under a servicing agreement\nDescription: A credit licensee acting on behalf of an exempt SPFE, such as a securitisation entity that makes (or buys) loans or leases and repackages them as investment products to sell to investors.\nDispute resolution requirements: When performing this role for an exempt SPFE, the credit licensee must: notify ASIC when they enter into a servicing agreement with an exempt SPFE and provide details of its membership with AFCA; and notify ASIC when they cease to be a party to the servicing agreement. The credit licensee should also ensure that their IDR process covers: the exempt SPFE’s activities; and complaints that arise when they act as the representative of the exempt SPFE and complaints about the conduct of the exempt SPFE. The credit licensee must inform a complainant of their right to complain to AFCA or directly refer them to AFCA.'},
  {'title': 'Dispute resolution requirements for fintech businesses relying on ERS exemption',
   'rg_refs': ['RG 271.4'],
   'chunk_type': 'requirement',
   'text': 'Financial technology (fintech) businesses relying on the enhanced regulatory sandbox (ERS) exemption provided by Corporations (FinTech Sandbox Australian Financial Services Licence Exemption) Regulations 2020 and National Consumer Credit Protection (FinTech Sandbox Australian Credit Licence Exemption) Regulations 2020 must have a dispute resolution system that consists of: an IDR procedure that complies with the standards and requirements made or approved by ASIC (set out in this guide); and membership of AFCA. Note: See Information Sheet 248 Enhanced regulatory sandbox (INFO 248) at Table 4.'}]}

In [38]:
agentic_chunks_sample_df = pd.DataFrame(agentic_result["chunks"])

print("Agentic sample chunks:", len(agentic_chunks_sample_df))

agentic_chunks_sample_df

Agentic sample chunks: 9

,title,rg_refs,chunk_type,text
0,Overview of dispute resolution system requirements,[RG 271.1],requirement,"Financial firms must have in place a dispute resolution system that consists of: (a) an IDR procedure that complies with standards and requirements made or approved by ASIC; and (b) membership of AFCA. Note 1: See s912A(1)(g) and 1017G(1) of the Corporations Act 2001 (Corporations Act), s47(1)(h..."
1,Compliance with IDR procedures by financial firms,[RG 271.2],requirement,"Most financial firms also have a requirement to comply with their IDR procedures: see modified s912A(1)(g) and 1017G(1) of the Corporations Act, and modified s47(1)(h) and (i) of the National Credit Act."
2,Modified regulatory regime for unlicensed credit firms,[RG 271.3],requirement,"A modified regulatory regime applies to some unlicensed credit firms. Credit representatives and exempt special purpose funding entities (exempt SPFEs) (including securitisation bodies) do not have IDR obligations, but must be a member of AFCA. Unlicensed carried over instrument lenders (unlicen..."
3,Dispute resolution requirements by firm type - Part 1,[RG 271.4],table,Table 1 sets out the dispute resolution requirements by type of financial firm.\n\nFirm type: Australian financial services (AFS) licensees\nDescription: An AFS licensee is a business carrying out financial services. This includes businesses that: provide financial product advice to clients; dea...
4,Dispute resolution requirements by firm type - Part 2,[RG 271.4],table,"Firm type: Superannuation trustees\nDescription: A trustee of a regulated superannuation fund (other than a self-managed superannuation fund (SMSF)), trustee of an approved deposit fund or a retirement savings account (RSA) provider.\nDispute resolution requirements: Superannuation trustees must..."
5,Dispute resolution requirements by firm type - Part 3,[RG 271.4],table,Firm type: Credit representatives\nDescription: A credit representative is a person authorised to engage in specified credit activities on behalf of a credit licensee under s64(2) or 65(2) of the National Credit Act. The employees and directors of a credit licensee do not need to be formally aut...
6,Dispute resolution requirements by firm type - Part 4,[RG 271.4],table,"Firm type: Unlicensed COI lenders (including prescribed unlicensed COI lenders)\nDescription: A ‘carried over instrument’ is a contract or other instrument that was made and in force, and to which an old Credit Code applied immediately before 1 July 2010 (see s4(1) of the National Consumer Credi..."
7,Dispute resolution requirements by firm type - Part 5,[RG 271.4],table,Firm type: Exempt SPFEs\nDescription: Special purpose funding entities (SPFEs) include securitisation entities and fundraising special purpose entities that make (or buy) loans or leases and repackage them as investment products to sell to investors. Note: See the definition of ‘special purpose ...
8,Dispute resolution requirements for fintech businesses relying on ERS exemption,[RG 271.4],requirement,Financial technology (fintech) businesses relying on the enhanced regulatory sandbox (ERS) exemption provided by Corporations (FinTech Sandbox Australian Financial Services Licence Exemption) Regulations 2020 and National Consumer Credit Protection (FinTech Sandbox Australian Credit Licence Exem...

In [39]:
for i, row in agentic_chunks_sample_df.iterrows():
    print(f"\n--- Agentic Chunk {i} ---")
    print("Title:", row["title"])
    print("RG refs:", row["rg_refs"])
    print("Type:", row["chunk_type"])
    print("Length:", len(row["text"]))
    print(row["text"][:1500])

--- Agentic Chunk 0 ---
Title: Overview of dispute resolution system requirements
RG refs: ['RG 271.1']
Type: requirement
Length: 678
Financial firms must have in place a dispute resolution system that consists of: (a) an IDR procedure that complies with standards and requirements made or approved by ASIC; and (b) membership of AFCA. Note 1: See s912A(1)(g) and 1017G(1) of the Corporations Act 2001 (Corporations Act), s47(1)(h) and (i) of the National Consumer Credit Protection Act 2009 (National Credit Act), s101(1) and (1A) of the Superannuation Industry (Supervision) Act 1993 (SIS Act), and s47(1) and (2) of the Retirement Savings Account Act 1997 (RSA Act). Note 2: Unlicensed carried over instrument lenders (unlicensed COI lenders) have IDR obligations, but are not required to be a member of AFCA.

--- Agentic Chunk 1 ---
Title: Compliance with IDR procedures by financial firms
RG refs: ['RG 271.2']
Type: requirement
Length: 203
Most financial firms also have a requirement to comply with their IDR procedures: see modified s912A(1)(g) and 1017G(1) of the Corporations Act, and modified s47(1)(h) and (i) of the National Credit Act.

--- Agentic Chunk 2 ---
Title: Modified regulatory regime for unlicensed credit firms
RG refs: ['RG 271.3']
Type: requirement
Length: 688
A modified regulatory regime applies to some unlicensed credit firms. Credit representatives and exempt special purpose funding entities (exempt SPFEs) (including securitisation bodies) do not have IDR obligations, but must be a member of AFCA. Unlicensed carried over instrument lenders (unlicensed COI lenders) have IDR obligations but are not required to be a member of AFCA. Note: See s64 and 65 of the National Credit Act, and regs 23B and 23C of the National Consumer Credit Protection Regulations 2010 (National Credit Regulations); see also reg 25E of the National Credit Regulations and s47(1)(e) of the National Credit Act (inserted by Sch 2 to the National Credit Regulations).

--- Agentic Chunk 3 ---
Title: Dispute resolution requirements by firm type - Part 1
RG refs: ['RG 271.4']
Type: table
Length: 1838
Table 1 sets out the dispute resolution requirements by type of financial firm.

Firm type: Australian financial services (AFS) licensees
Description: An AFS licensee is a business carrying out financial services. This includes businesses that: provide financial product advice to clients; deal in a financial product; make a market for a financial product; operate a registered scheme; provide a custodial or depository service; or provide traditional trustee company services (traditional services).
Dispute resolution requirements: AFS licensees must have a dispute resolution system that consists of: an IDR procedure that complies with the standards and requirements made or approved by ASIC (set out in this guide) that cover complaints made by retail clients in relation to the financial services provided; and membership of AFCA. AFS licensees must also comply with their IDR procedure. Note: See s912A(1)(g) of the Corporations Act.

Firm type: Unlicensed product issuers and unlicensed secondary sellers
Description: An unlicensed product issuer is an issuer of a financial product who is not an AFS licensee. An unlicensed secondary seller is a person who offers the secondary sale of a financial product under s1012C(5)(b) or (8) of the Corporations Act and who is not an AFS licensee.
Dispute resolution requirements: Unlicensed product issuers and unlicensed secondary sellers are required to have a dispute resolution system that consists of: an IDR procedure that complies with the st

--- Agentic Chunk 4 ---
Title: Dispute resolution requirements by firm type - Part 2
RG refs: ['RG 271.4']
Type: table
Length: 1593
Firm type: Superannuation trustees
Description: A trustee of a regulated superannuation fund (other than a self-managed superannuation fund (SMSF)), trustee of an approved deposit fund or a retirement savings account (RSA) provider.
Dispute resolution requirements: Superannuation trustees must: be a member of AFCA; and have an IDR procedure that complies with the standards and requirements set out in s912A(2)(a)(i) of the Corporations Act. Note 1: See also s101(1)(a)–(c) of the SIS Act. Note 2: However, s101(1)(a)–(c) of the SIS Act does not apply to a trustee if the trustee is required under the Corporations Act to have a dispute resolution system complying with s912A(2) or 1017G(2) of the Act.

Firm type: Australian credit licensees (credit licensees)
Description: Credit providers and lessors, including those who are assigned the contractual rights of a credit provider or lessor (which can include debt collectors who purchase a debt from a credit provider or lessor). Credit service providers (such as brokers and other intermediaries), and others (such as debt collectors) who act on behalf of the credit provider or lessor.
Dispute resolution requirements: Credit licensees are required to have a dispute resolution system that consists of: an IDR procedure that complies with the standards and requirements made or approved by ASIC (set out in this guide) that cover disputes relating to credit activities they and their representatives engage in; and membership of AFCA. Credit li

--- Agentic Chunk 5 ---
Title: Dispute resolution requirements by firm type - Part 3
RG refs: ['RG 271.4']
Type: table
Length: 1132
Firm type: Credit representatives
Description: A credit representative is a person authorised to engage in specified credit activities on behalf of a credit licensee under s64(2) or 65(2) of the National Credit Act. The employees and directors of a credit licensee do not need to be formally authorised—they act as representatives of the credit licensee without a specific authorisation. A person can also be authorised as a credit representative by more than one credit licensee.
Dispute resolution requirements: Credit representatives do not need to have IDR processes that meet the standards and requirements made or approved by ASIC. This is because a credit licensee’s IDR process must cover disputes relating to its credit representatives. Most credit representatives are required to be separate members of AFCA: see s64 and 65 of the National Credit Act. However, a person who has been sub-authorised under s65(1) of the National Credit Act and is an employee or director of the body corporate that gave the sub-authorisation does not need to be a separate member of AFCA. Note: See reg 16 of the National Credit Regulations.

--- Agentic Chunk 6 ---
Title: Dispute resolution requirements by firm type - Part 4
RG refs: ['RG 271.4']
Type: table
Length: 3161
Firm type: Unlicensed COI lenders (including prescribed unlicensed COI lenders)
Description: A ‘carried over instrument’ is a contract or other instrument that was made and in force, and to which an old Credit Code applied immediately before 1 July 2010 (see s4(1) of the National Consumer Credit Protection (Transitional and Consequential Provisions) Act 2009). Unlicensed COI lenders are credit providers or lessors who only have a closed pool of carried over instruments and have chosen not to obtain a credit licence (or to restrict their activities to their carried over instruments, and subsequently cancel their credit licence).
Note: A ‘prescribed unlicensed COI lender’ is an unlicensed COI lender who fails to meet certain probity requirements and who has restrictions placed on their conduct in relation to their carried over instruments. A prescribed unlicensed COI lender must not engage in credit activities with respect to their carried over instruments (other than the activities engaged in solely by being the credit provider or lessor). They must instead appoint a credit licensee to act as a ‘representative’ to engage in credit activities on their behalf with respect to their carried over instruments.
Dispute resolution requirements: Unlicensed COI lenders (including prescribed unlicensed COI lenders): must have an IDR procedure that complies with the standards and requirements made or approved by ASIC (set out in this guide) that cover complaints in relation to the credit

--- Agentic Chunk 7 ---
Title: Dispute resolution requirements by firm type - Part 5
RG refs: ['RG 271.4']
Type: table
Length: 2284
Firm type: Exempt SPFEs
Description: Special purpose funding entities (SPFEs) include securitisation entities and fundraising special purpose entities that make (or buy) loans or leases and repackage them as investment products to sell to investors. Note: See the definition of ‘special purpose funding’ entity in s5 of the National Credit Act (inserted by Sch 3 to the National Credit Regulations). SPFEs can either operate under a credit licence or as exempt SPFEs: see the licensing exemption in regs 23B and 23C of the National Credit Regulations. Note: See the definition of ‘exempt special purpose funding entity’ in reg 3 of the National Credit Regulations.
Dispute resolution requirements: Exempt SPFEs may rely on a licensing exemption: see regs 23B and 23C of the National Credit Regulations. If they do, they must: enter into a servicing agreement with a credit licensee under which that licensee acts on their behalf; and be a member of AFCA. Exempt SPFEs do not have any IDR requirements. We expect that the credit licensee’s IDR process will cover complaints about both: credit activities engaged in by the licensee under a servicing agreement; and conduct of the exempt SPFE (including where changes are sought to the terms of the contract—for example, on the basis of hardship or because the contract was unsuitable or unjust).

Firm type: Credit licensees acting on behalf of exempt SPFEs under a servicing agreement
Description: A credit licensee acting on behalf of an exempt SPFE,

--- Agentic Chunk 8 ---
Title: Dispute resolution requirements for fintech businesses relying on ERS exemption
RG refs: ['RG 271.4']
Type: requirement
Length: 599
Financial technology (fintech) businesses relying on the enhanced regulatory sandbox (ERS) exemption provided by Corporations (FinTech Sandbox Australian Financial Services Licence Exemption) Regulations 2020 and National Consumer Credit Protection (FinTech Sandbox Australian Credit Licence Exemption) Regulations 2020 must have a dispute resolution system that consists of: an IDR procedure that complies with the standards and requirements made or approved by ASIC (set out in this guide); and membership of AFCA. Note: See Information Sheet 248 Enhanced regulatory sandbox (INFO 248) at Table 4.

## Agentic Chunking Result

The agentic chunking method produced the strongest chunk quality.

Compared with recursive, semantic, paragraph-aware, and RG-number-aware approaches, the agentic method better preserved regulatory meaning, RG references, headings, and sentence boundaries.

The resulting chunks are readable as standalone retrieval units and include useful metadata such as title, RG references, and chunk type.

For this project, agentic chunking is selected as the primary chunking strategy. Long table-based chunks will still be reviewed and split into logical subparts when needed.